# Dockerfile for NEON IS Data Processing - Fill date gaps in repo structured by location

# Start with the base image. 
FROM quay.io/battelleecology/neon-is-base-r:v0.0.27

# maintainer handle
MAINTAINER "Cove Sturtevant" csturtevant@battelleecology.org

# Copy in calibration filter workflow
COPY ./flow.loc.repo.gf.R /flow.loc.repo.gf.R
