# Environment variables for the cmp22 calibration group and convert module
# To load this configmap in kubernetes:
#   kubectl config set-context --current --namespace=argo-workflows-dev
#   kubectl apply -f <configmapFile> 
apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp22-cal-group-convert-env
  namespace: argo-workflows-dev
  labels:
    # Note: This label is required for the informer to detect this ConfigMap.
    workflows.argoproj.io/configmap-type: Parameter
data:
  # Workflow-level parameters
  log-level: INFO
  err-path: /pfs/errored_datums # All modules that produce errored datums
  schema-repo-eng-url: git@github.com:BattelleEcology/neon-avro-schemas.git
  schema-repo-eng-revision: develop # Branch or tag
  schema-repo-sci-url: https://github.com/NEONScience/NEON-IS-avro-schemas.git
  schema-repo-sci-revision: master # Branch or tag
  parallelism-internal: "3" # Internal R parallelization for all R modules
  
  # Parameters for input data load
  l0-bucket-name: neon-dev-l0-ingest # STILL WORKING ON THIS
  l0-bucket-version-path: v2
  cal-bucket-name: neon-dev-argo-workflow-test # STILL WORKING ON THIS 
  source-type-index: "0" # Index in the manifest path  (must be present)
  year-index: "1" # Index in the manifest path (doesn't actually need to be present)
  month-index: "2" # Index in the manifest path (doesn't actually need to be present)
  day-index: "3" # Index in the manifest path (doesn't actually need to be present)
  source-id-index: "4" # Index in the manifest path (doesn't actually need to be present)
  out-path-l0: /inputs/DATA_PATH_ARCHIVE

 # Parameters for filter-joiner merging calibrations with data
  filter-joiner-config: |
    ---
    # Configuration for filter-joiner module that will bring together the data and calibrations
    # In Pachyderm root will be index 0, 'pfs' index 1, and the repo name index 2.
    # Metadata indices will typically begin at index 3.
    input_paths:
    - path:
        name: DATA_PATH_ARCHIVE
        # Filter for data directory
        glob_pattern: /inputs/DATA_PATH_ARCHIVE/cmp22/*/*/*/*/**
        # Join on named location (already joined below by day)
        join_indices: [7]
        outer_join: true
    - path:
        name: CALIBRATION_PATH
        # Filter for data directory
        glob_pattern: /inputs/CALIBRATION_PATH/cmp22/*/*/*/*/**
        # Join on named location (already joined below by day)
        join_indices: [7]
        outer_join: true
  relative-path-index: "3"
  link-type: SYMLINK
  out-path-joiner: /pfs/data_cal_joined

  # Command line arguments and other input params for flow.kfka.comb.R
  kfka-comb-r-args: >
    DirIn=$OUT_PATH_JOINER
    DirOut=$OUT_PATH_KAFKA_COMB
    DirErr=$ERR_PATH
    FileSchmL0=$FILE_SCHEMA_L0
    DirSubCopy=calibration
  out-path-kafka-comb: /pfs/kafka_combined
  file-schema-l0: /inputs/schemas-eng/schemas/cmp22/cmp22.avsc

  # Command line arguments and other input params for flow.cal.conv.R
  cal-conv-r-args: >
    DirIn=$OUT_PATH_KAFKA_COMB
    DirOut=$OUT_PATH_CAL_CONV
    DirErr=$ERR_PATH
    FileSchmData=$FILE_SCHEMA_CALIBRATED_DATA
    FileSchmQf=$FILE_SCHEMA_CALIBRATION_FLAGS
    ConvFuncTerm1=def.cal.conv.poly:voltage
    TermQf=voltage
    UcrtFuncTerm1=def.ucrt.meas.mult:voltage
    UcrtFuncTerm2=def.ucrt.fdas.volt.poly:voltage
    FileUcrtFdas=$FILE_UNCERTAINTY_FDAS
  file-schema-calibrated-data: /inputs/schemas-sci/avro_schemas/cmp22/cmp22_calibrated.avsc
  file-schema-calibration-flags: /inputs/schemas-sci/avro_schemas/cmp22/flags_calibration_cmp22.avsc
  out-path-cal-conv: /pfs/cmp22_calibration_group_and_convert
  file-uncertainty-fdas: /inputs/schemas-sci/uncertainty_fdas/fdas_calibration_uncertainty_general.json

  # Parameters for data upload to bucket
  output-bucket-name: neon-dev-argo-workflow-test
  output-bucket-prefix: cmp22_calibration_group_and_convert # Output Repo name