# Dockerfile for NEON IS Data Processing - Truncate and merge data files by location

# Start with the base image. 
FROM quay.io/battelleecology/neon-is-base-r:v0.0.30

# maintainer handle
MAINTAINER "Cove Sturtevant" csturtevant@battelleecology.org

# Copy in calibration filter workflow
COPY ./flow.loc.data.trnc.comb.R /flow.loc.data.trnc.comb.R
