---
pipeline:
  name: rmyoung_hmr3300_fill_date_gaps
transform:
  image: us-central1-docker.pkg.dev/neon-shared-service/neonscience/neon-is-gap-fill-nonrglr:v1.0.3
  cmd:
  - sh
  - "-c"
  - |-
    /bin/bash <<'EOF'
    # Use bash-strict mode. See http://redsymbol.net/articles/unofficial-bash-strict-mode/
    set -euo pipefail
    IFS=$'\n\t'

    # Refresh interim directories with each datum (otherwise they persist and cause probs)
    rm -rf $OUT_PATH
    mkdir -p $OUT_PATH

    # Get source type /SOURCE_TYPE/YYYY/MM/DD 
    if [ ${LOCATION_PATH+x} ]; then 
      source_type=$(echo $LOCATION_PATH | cut -f 4 -d "/")
      echo "Source type: $source_type"
    else
      echo "LOCATION_PATH does not exist (no locations active for datum $DATA_PATH). Skipping..."
      exit 0
    fi

    # Get empty file path based on source type
    if [ $source_type = "rmyoung" ]; then 
      export EMPTY_FILE_PATH="/pfs/EMPTY_FILES/rmyoung"
      export OUTPUT_DIRECTORIES="data,location,uncertainty_data,uncertainty_coef,flags"
    elif [ $source_type = "hmr3300" ]; then 
      export EMPTY_FILE_PATH="/pfs/EMPTY_FILES/hmr3300"
      export OUTPUT_DIRECTORIES="data,location"
    else
      echo "No source type determined. Check inputs."
      exit 1
    fi
    
    # Run first module - date-gap-filler (using environment variables below as input parameters)
    python3 -m date_gap_filler.date_gap_filler_main
    
    #run gap filler for nonregularized data
    if [ $source_type = "rmyoung" ]; then 
      Rscript ./flow.gap.fill.nonrglr.R \
        DirIn=/tmp/pfs/date_filled \
        DirOut=/pfs/out \
        DirErr=/pfs/out/errored_datums \
        "DirFill=data|uncertainty_data|flags" \
        WndwFill="01" \
        "DirSubCopy=location|uncertainty_coef" \
        "FileSchm=data:$SCHEMA_DATA_RMYOUNG|flags:$SCHEMA_FLAGS_RMYOUNG"
    elif [ $source_type = "hmr3300" ]; then
      Rscript ./flow.gap.fill.nonrglr.R \
        DirIn=/tmp/pfs/date_filled \
        DirOut=/pfs/out \
        DirErr=/pfs/out/errored_datums \
        "DirFill=data" \
        WndwFill="01" \
        "DirSubCopy=location" \
        "FileSchm=data:$SCHEMA_DATA_HMR3300"
    fi
    EOF
  env:
    # Environment variables for date gap filler
    LOG_LEVEL: DEBUG
    OUT_PATH: /tmp/pfs/date_filled
    DATA_SOURCE_TYPE_INDEX: '3'
    DATA_YEAR_INDEX: '4'
    DATA_MONTH_INDEX: '5'
    DATA_DAY_INDEX: '6'
    DATA_LOCATION_INDEX: '7'
    DATA_TYPE_INDEX: '8'
    LOCATION_SOURCE_TYPE_INDEX: '3'
    LOCATION_YEAR_INDEX: '4'
    LOCATION_MONTH_INDEX: '5'
    LOCATION_DAY_INDEX: '6'
    LOCATION_INDEX: '7'
    EMPTY_FILE_TYPE_INDEX: '4'
    LINK_TYPE: COPY # options are COPY or SYMLINK. Use COPY for combined modules.
    # Environment variables for regularizer
    PARALLELIZATION_INTERNAL: '3' # Parallelization within R. If increased, adjust resource requests appropriately.
input:
  cross:
  - pfs:
      name: EMPTY_FILES
      repo: rmyoung_hmr3300_empty_files
      glob: /
      empty_files: false # Make sure to use false if LINK_TYPE=COPY. Can also be set to false for LINK_TYPE=SYMLINK.
  - pfs:
      name: SCHEMA_DATA_RMYOUNG
      repo: rmyoung_hmr3300_avro_schemas
      glob: /rmyoung/rmyoung_calibrated.avsc
  - pfs:
      name: SCHEMA_FLAGS_RMYOUNG
      repo: rmyoung_hmr3300_avro_schemas
      glob: /rmyoung/rmyoung_calibration_flags.avsc
  - pfs:
      name: SCHEMA_DATA_HMR3300
      repo: rmyoung_hmr3300_avro_schemas
      glob: /hmr3300/hmr3300_l0.avsc
  - group:
    - pfs:
        name: DATA_PATH
        repo: rmyoung_hmr3300_location_group_and_restructure
        glob: /(*/*/*/*)
        group_by: $1
        empty_files: false # Make sure to use false if LINK_TYPE=COPY. Can also be set to false for LINK_TYPE=SYMLINK.
    - join:
      - pfs:
          name: LOCATION_PATH
          repo: rmyoung_hmr3300_location_active_dates_assignment
          glob: /(*/*/*/*)
          joinOn: $1
          group_by: $1
          empty_files: false # Make sure to use false if LINK_TYPE=COPY. Can also be set to false for LINK_TYPE=SYMLINK.
      - pfs:
          name: DATE_LIMITER_PATH
          repo: rmyoung_hmr3300_cron_daily_and_date_control
          glob: /(*/*/*/*)
          joinOn: $1
          group_by: $1
          empty_files: true # This can remain true even if LINK_TYPE=COPY
parallelism_spec:
  constant: 5
autoscaling: true
resource_requests:
  memory: 2G
  cpu: 3.3
resource_limits:
  memory: 3G
  cpu: 4.5
sidecar_resource_requests:
  memory: 3G
  cpu: 0.5
datum_set_spec:
  number: 1
scheduling_spec:
  node_selector:
    cloud.google.com/compute-class: pach-pipeline-class
