---
pipeline:
  name: rmyoung_hmr3300_calibration_group_and_convert
transform:
  image: us-central1-docker.pkg.dev/neon-shared-service/neonscience/neon-is-cal-grp-conv:sha-fb97d23
  cmd:
  - sh
  - "-c"
  - |-
    /bin/bash <<'EOF'
    # Use bash-scrict mode. See http://redsymbol.net/articles/unofficial-bash-strict-mode/
    set -euo pipefail
    IFS=$'\n\t'
    
    # Refresh interim directories with each datum (otherwise they persist and cause probs)
    rm -r -f /tmp/pfs/rmyoung_filter_joined
    rm -rf /tmp/pfs/rmyoung
    mkdir -p /tmp/pfs/rmyoung_filter_joined
    mkdir -p /tmp/pfs/rmyoung

    # Set some environment variables for the first module
    export OUT_PATH=$OUT_PATH_1
    
    # Run filter-joiner for data (using environment variables below as input parameters)
    echo "Running filter-joiner with OUT_PATH=$OUT_PATH"
    python3 -m filter_joiner.filter_joiner_main

    # Run calibration conversion module
    #hmr3300 not calibrated, so only run for rmyoung
    Rscript ./flow.cal.conv.R \
        DirIn=/tmp/pfs/rmyoung_filter_joined \
        DirOut=/tmp/pfs \
        DirErr=/pfs/out/errored_datums \
        "ConvFuncTerm1=def.cal.conv.nmnl:speed" \
        "ConvFuncTerm2=def.cal.conv.nmnl:direction" \
        "Meta=speed:0.1666667,CVALB1|direction:355,CVALA1" \
        "TermQf=speed|direction" \
        "UcrtFuncTerm1=def.ucrt.meas.cnst:speed" \
        "UcrtFuncTerm2=def.ucrt.meas.cnst:direction" \
        FileSchmData=$SCHEMA_CAL_RMYOUNG \
        FileSchmQf=$SCHEMA_FLAGS_RMYOUNG 
    
    # Set some environment variables for the second filter joiner
    export OUT_PATH=$OUT_PATH_2
    export CONFIG=$CONFIG2

    # Run second module - filter-joiner to bring in SRF (using environment variables below as input parameters)
    python3 -m filter_joiner.filter_joiner_main

    EOF
  env:
    # Environment variables for filter-joiner.
    CONFIG: |
      ---
      # Configuration for filter-joiner module that will bring together the data and calibrations
      # In Pachyderm root will be index 0, 'pfs' index 1, and the repo name index 2.
      # Metadata indices will typically begin at index 3.
      input_paths:
        - path:
            name: DATA_PATH
            # Filter for data directory
            glob_pattern: /pfs/DATA_PATH_RMYOUNG/rmyoung/*/*/*/*/**
            # Join on named location (already joined below by source type and day)
            join_indices: [7]
            outer_join: True
        - path:
            name: CALIBRATION_PATH
            glob_pattern: /pfs/CALIBRATION_PATH/rmyoung/*/*/*/*/**
            # Join on named location (already joined below by day)
            join_indices: [7]
    LOG_LEVEL: INFO
    OUT_PATH_1: /tmp/pfs/rmyoung_filter_joined
    RELATIVE_PATH_INDEX: "3" # Must be consistent across inputs 
    LINK_TYPE: COPY # options are COPY or SYMLINK. 
    # Environment variables for calibration module
    PARALLELIZATION_INTERNAL: '3' # Option for calibration conversion module
    # Environment variables for bash code

    # Below are the environment variables for 2nd filter-joiner 
    CONFIG2: |
      ---
      # In Pachyderm root will be index 0, 'pfs' index 1, and the repo name index 2.
      # Metadata indices will typically begin at index 3.
      # Use unix-style glob pattern to select the desired directories in each repo 
      input_paths:
        - path:
            name: CALIBRATED_RMYOUNG_PATH
            # Filter for data directory
            glob_pattern: /tmp/pfs/rmyoung/**
            # Join on group ID (already joined below by day)
            join_indices: [6]
            outer_join: True
        - path:
            name: HMR3300_PATH
            # Filter for data directory
            glob_pattern: /pfs/DATA_PATH_HMR3300/**
            # Join on group ID(already joined below by day)
            join_indices: [6]
            outer_join: True
    OUT_PATH_2: /pfs/out # This will be transfered to OUT_PATH for the this module

input:
  cross:
  - pfs:
      name: SCHEMA_CAL_RMYOUNG
      repo: rmyoung_hmr3300_avro_schemas
      glob: /rmyoung/rmyoung_calibrated.avsc
  - pfs:
      name: SCHEMA_FLAGS_RMYOUNG
      repo: rmyoung_hmr3300_avro_schemas
      glob: /rmyoung/rmyoung_calibration_flags.avsc
  - pfs:
      name: SCHEMA_L0_HMR3300
      repo: rmyoung_hmr3300_avro_schemas
      glob: /hmr3300/hmr3300_l0.avsc
  - join:
    - pfs:
        name: CALIBRATION_PATH
        repo: rmyoung_calibration_assignment
        glob: /rmyoung/(*)/(*)/(*)
        joinOn: $1/$2/$3
        outer_join: true
        empty_files: false # Make sure to use false if LINK_TYPE=COPY. Can also be set to false for LINK_TYPE=SYMLINK.
    - pfs:
        name: DATA_PATH_RMYOUNG
        repo: rmyoung_hmr3300_data_source_trino
        glob: /rmyoung/(*)/(*)/(*)
        joinOn: $1/$2/$3
        outer_join: true
        empty_files: false # Make sure to use false if LINK_TYPE=COPY. Can also be set to false for LINK_TYPE=SYMLINK.
    - pfs:
        name: DATA_PATH_HMR3300
        repo: rmyoung_hmr3300_data_source_trino
        glob: /hmr3300/(*)/(*)/(*)
        joinOn: $1/$2/$3
        outer_join: true
        empty_files: false # Make sure to use false if LINK_TYPE=COPY. Can also be set to false for LINK_TYPE=SYMLINK.
parallelism_spec:
  constant: 5
autoscaling: true
resource_requests:
  memory: 1.2G
  cpu: 1.3
resource_limits:
  memory: 2G
  cpu: 2
sidecar_resource_requests:
  memory: 1G
  cpu: 0.5
datum_set_spec:
  number: 5
scheduling_spec:
  node_selector:
    cloud.google.com/compute-class: pach-pipeline-class
