---
pipeline:
  name: exo2_replace_sn_with_assetuid
transform:
  # image_pull_secrets: [battelleecology-quay-read-all-pull-secret]
  image: us-central1-docker.pkg.dev/neon-shared-service/neonscience/neon-is-sn-to-asset-uid:sha-d9e7bbf
  cmd:
  - sh
  - "-c"
  - |-
    /bin/bash <<'EOF'
    # Use bash-scrict mode. See http://redsymbol.net/articles/unofficial-bash-strict-mode/
    set -euo pipefail
    IFS=$'\n\t' 
    export DATA_PATH=$DATA_PATH
    python3 -m replace_sn_with_assetuid.replace_sn_with_assetuid_main
  env:
    OUT_PATH: /pfs/out
    RELATIVE_PATH_INDEX: "3"
    LOG_LEVEL: DEBUG
    # LINK_TYPE: SYMLINK # options are COPY or SYMLINK
input:
  cross:
  - pfs:
      name: MAP_PATH
      repo: exo2_sn_assetuid_mapping_loader
      glob: /*
  - pfs:
      name: DATA_PATH
      repo: exo2_logjam_assign_clean_files
      glob: /*/(*/*/*)
parallelism_spec:
  constant: 1
autoscaling: true
resource_requests:
  memory: 1G
  cpu: 1.0
resource_limits:
  memory: 3G
  cpu: 4.5
sidecar_resource_requests:
  memory: 3G
  cpu: 0.6
datum_set_spec:
  number: 1
scheduling_spec:
  node_selector:
    cloud.google.com/compute-class: pach-pipeline-class
