---
pipeline:
  name: exo2_logjam_parse_by_day
transform:
  image: us-central1-docker.pkg.dev/neon-shared-service/neonscience/neon-is-exo2-logs-load-clean-assign:sha-
  cmd: ["/bin/bash"]
  stdin:
  - "#!/bin/bash"
  - Rscript ./flow.exo2.logfiles.parse.R \
      DirIn=$DIR_IN
      DirOut=/pfs/out
      DirErr=/pfs/out/errored_datums
      FileSchmData=$SCHEMA_DATA
      FileSchmQf=$SCHEMA_FLAGS
  env:
    LOG_LEVEL: DEBUG
input:
  cross:
  - pfs:
      name: DIR_IN
      repo: exo2_logs_load_clean_assign
      # /YYYY/MM/DD/group/sourcetype/CFGLOC
      glob: /*/*/*
  - pfs:
      name: SCHEMA_FLAGS
      repo: nitrate_avro_schemas
      glob: /exo2/
parallelism_spec:
  constant: 6
autoscaling: true
resource_requests:
  memory: 1G
  cpu: 1.2
resource_limits:
  memory: 2G
  cpu: 2
sidecar_resource_requests:
  memory: 2G
  cpu: 0.5
datum_set_spec:
  number: 1
scheduling_spec:
  node_selector:
    cloud.google.com/compute-class: pach-pipeline-class
