---
pipeline:
  name: exo2_sn_assetuid_mapping_loader
transform:
  image_pull_secrets:
  - battelleecology-quay-read-all-pull-secret
  image: us-central1-docker.pkg.dev/neon-shared-service/neonscience/neon-is-sn-asset-map:sha-0054eb6
  cmd:
  - /bin/bash
  stdin:
  - '#!/bin/bash'
  - export SOURCE_TYPE=$SOURCE_TYPE_1
  - python3 -m sn_assetuid_mapping_loader.sn_assetuid_mapping_loader
  - export SOURCE_TYPE=$SOURCE_TYPE_2
  - python3 -m sn_assetuid_mapping_loader.sn_assetuid_mapping_loader
  - export SOURCE_TYPE=$SOURCE_TYPE_3
  - python3 -m sn_assetuid_mapping_loader.sn_assetuid_mapping_loader
  - export SOURCE_TYPE=$SOURCE_TYPE_4
  - python3 -m sn_assetuid_mapping_loader.sn_assetuid_mapping_loader
  - export SOURCE_TYPE=$SOURCE_TYPE_5
  - python3 -m sn_assetuid_mapping_loader.sn_assetuid_mapping_loader
  - export SOURCE_TYPE=$SOURCE_TYPE_6
  - python3 -m sn_assetuid_mapping_loader.sn_assetuid_mapping_loader
  env:
    OUTPUT_PATH: /pfs/out
    REGION: cert
    SOURCE_TYPE_1: exo2
    SOURCE_TYPE_2: exo2conductivity
    SOURCE_TYPE_3: exo2turbidity
    SOURCE_TYPE_4: exo2fdom
    SOURCE_TYPE_5: exo2phorp
    SOURCE_TYPE_6: exo2dissolvedoxygen
    CDSWEBAPP_URL: http://den-certcdsllb-1.ci.neoninternal.org/cdsWebApp/
    LOG_LEVEL: DEBUG
  secrets:
  - name: pdr-secret
    mount_path: /var/db_secret
  - name: cds-secret
    mount_path: /var/cds_secret
input:
  pfs:
    repo: exo2_cron_daily_and_date_control_tick
    glob: /*
    empty_files: true
autoscaling: true
resource_requests:
  memory: 100M
  cpu: 0.05
resource_limits:
  memory: 300M
  cpu: 0.5
sidecar_resource_requests:
  memory: 3G
  cpu: 0.5
scheduling_spec:
  node_selector:
    cloud.google.com/compute-class: pach-pipeline-class
