---
pipeline:
  name: exo2_logjam_assign_clean_files
transform:
  image: us-central1-docker.pkg.dev/neon-shared-service/neonscience/neon-is-exo2-logs-load-clean-assign:sha-a825040
  cmd: ["/bin/bash"]
  stdin:
  - "#!/bin/bash"
  - set -x
  - Rscript ./flow.exo2.logfiles.R \
      DirIn=$DIR_IN
      DirOutBase=/pfs/out
      DirErr=/pfs/out/errored_datums
      SchmExo2=$SCHEMA_EXO2
      SchmCond=$SCHEMA_COND
      SchmDO=$SCHEMA_DO
      SchmPh=$SCHEMA_PH
      SchmTurb=$SCHEMA_TURB
      SchmFdom=$SCHEMA_FDOM
      SchmChl=$SCHEMA_CHL
      SchmFlagsExo2=$SCHEMA_FLAGS_EXO2
      SchmFlagsCond=$SCHEMA_FLAGS_COND
      SchmFlagsDO=$SCHEMA_FLAGS_DO
      SchmFlagsPh=$SCHEMA_FLAGS_PH
      SchmFlagsTurb=$SCHEMA_FLAGS_TURB
      SchmFlagsFdom=$SCHEMA_FLAGS_FDOM
      SchmFlagsChl=$SCHEMA_FLAGS_CHL
  env:
    LOG_LEVEL: DEBUG
input:
  cross:
  - pfs:
      name: DIR_IN
      repo: exo2_logjam_load_files
      glob: /*
  - pfs:
      name: SCHEMA_EXO2
      repo: exo2_avro_schemas
      glob: /exo2/exo2_calibrated.avsc
  - pfs:
      name: SCHEMA_COND
      repo: exo2_avro_schemas
      glob: /exoconductivity/exoconductivity_calibrated.avsc
  - pfs:
      name: SCHEMA_DO
      repo: exo2_avro_schemas
      glob: /exodissolvedoxygen/exodissolvedoxygen_calibrated.avsc
  - pfs:
      name: SCHEMA_PH
      repo: exo2_avro_schemas
      glob: /exophorp/exophorp_calibrated.avsc
  - pfs:
      name: SCHEMA_TURB
      repo: exo2_avro_schemas
      glob: /exoturbidity/exoturbidity_calibrated.avsc
  - pfs:
      name: SCHEMA_FDOM
      repo: exo2_avro_schemas
      glob: /exofdom/exofdom_calibrated.avsc
  - pfs:
      name: SCHEMA_CHL
      repo: exo2_avro_schemas
      glob: /exototalalgae/exototalalgae_calibrated.avsc
  - pfs:
      name: SCHEMA_FLAGS_EXO2
      repo: exo2_avro_schemas
      glob: /exo2/flags_logs_exo2.avsc
  - pfs:
      name: SCHEMA_FLAGS_COND
      repo: exo2_avro_schemas
      glob: /exoconductivity/flags_logs_exoconductivity.avsc
  - pfs:
      name: SCHEMA_FLAGS_DO
      repo: exo2_avro_schemas
      glob: /exodissolvedoxygen/flags_logs_exodissolvedoxygen.avsc
  - pfs:
      name: SCHEMA_FLAGS_PH
      repo: exo2_avro_schemas
      glob: /exophorp/flags_logs_exophorp.avsc
  - pfs:
      name: SCHEMA_FLAGS_TURB
      repo: exo2_avro_schemas
      glob: /exoturbidity/flags_logs_exoturbidity.avsc
  - pfs:
      name: SCHEMA_FLAGS_FDOM
      repo: exo2_avro_schemas
      glob: /exofdom/flags_logs_exofdom.avsc
  - pfs:
      name: SCHEMA_FLAGS_CHL
      repo: exo2_avro_schemas
      glob: /exototalalgae/flags_logs_exototalalgae.avsc
parallelism_spec:
  constant: 5
autoscaling: true
resource_requests:
  memory: 2G
  cpu: 3.3
resource_limits:
  memory: 3G
  cpu: 4.5
sidecar_resource_requests:
  memory: 4G
  cpu: 2
datum_set_spec:
  number: 1
scheduling_spec:
  node_selector:
    cloud.google.com/compute-class: pach-pipeline-class