---
pipeline:
  name: exo2_logjam_assign_clean_files
transform:
  image: us-central1-docker.pkg.dev/neon-shared-service/neonscience/neon-is-exo2-logs-load-clean-assign:sha-8534fd9
  cmd: ["/bin/bash"]
  stdin:
  - "#!/bin/bash"
  - set -x
  - Rscript ./flow.exo2.logfiles.R \
      DirIn=$DIR_IN
      DirOutBase=/pfs/out
      DirErr=/pfs/out/errored_datums
      SchmExo2=$SCHEMA_EXO2
      SchmCond=$SCHEMA_COND
      SchmDO=$SCHEMA_DO
      SchmPh=$SCHEMA_PH
      SchmTurb=$SCHEMA_TURB
      SchmFdom=$SCHEMA_FDOM
      SchmChl=$SCHEMA_CHL
  env:
    LOG_LEVEL: DEBUG
input:
  cross:
  - pfs:
      name: DIR_IN
      repo: exo2_logjam_load_files
      glob: /*
  - pfs:
      name: SCHEMA_EXO2
      repo: exo2_avro_schemas
      glob: /exo2/exo2_log_data.avsc
  - pfs:
      name: SCHEMA_COND
      repo: exo2_avro_schemas
      glob: /exo2conductivity/exo2conductivity_log_data.avsc
  - pfs:
      name: SCHEMA_DO
      repo: exo2_avro_schemas
      glob: /exo2dissolvedoxygen/exo2dissolvedoxygen_log_data.avsc
  - pfs:
      name: SCHEMA_PH
      repo: exo2_avro_schemas
      glob: /exo2phorp/exo2phorp_log_data.avsc
  - pfs:
      name: SCHEMA_TURB
      repo: exo2_avro_schemas
      glob: /exo2turbidity/exo2turbidity_log_data.avsc
  - pfs:
      name: SCHEMA_FDOM
      repo: exo2_avro_schemas
      glob: /exo2fdom/exo2fdom_log_data.avsc
  - pfs:
      name: SCHEMA_CHL
      repo: exo2_avro_schemas
      glob: /exo2algae/exo2algae_log_data.avsc
parallelism_spec:
  constant: 5
autoscaling: true
resource_requests:
  memory: 2G
  cpu: 3.3
resource_limits:
  memory: 3G
  cpu: 4.5
sidecar_resource_requests:
  memory: 4G
  cpu: 2
datum_set_spec:
  number: 1
scheduling_spec:
  node_selector:
    cloud.google.com/compute-class: pach-pipeline-class