---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo-workflows-dev
resources:
  - location_asset_assignment_config.yaml
  - configmap_location_asset_assignment_env.yaml
  - location_asset_assignment.yaml