#!/usr/bin/env python3
"""
Create a sourceable shell script from processing instructions YAML.

Expected YAML structures:

commands:
    - |
        <shell command block>
    - |
        <another shell command block>

or:

commands: |
    <shell command block>
    <another shell command block>

The generated script contains commands in the same order.
"""

import os
import sys
from pathlib import Path

import yaml


def load_instructions(input_file: str) -> dict:
    """Load and validate YAML instructions file."""
    try:
        with open(input_file, "r") as f:
            payload = yaml.safe_load(f)
    except FileNotFoundError:
        print(f"ERROR: Instructions file not found: {input_file}", file=sys.stderr)
        sys.exit(1)
    except yaml.YAMLError as e:
        print(f"ERROR: Failed to parse instructions YAML: {e}", file=sys.stderr)
        sys.exit(1)

    if payload is None:
        print("ERROR: Instructions YAML is empty.", file=sys.stderr)
        sys.exit(1)
    if not isinstance(payload, dict):
        print("ERROR: Instructions YAML must contain a top-level mapping.", file=sys.stderr)
        sys.exit(1)

    commands = payload.get("commands")
    if isinstance(commands, str):
        if not commands.strip():
            print("ERROR: 'commands' scalar block must be non-empty.", file=sys.stderr)
            sys.exit(1)
        payload["commands"] = [commands]
        return payload

    if not isinstance(commands, list) or not commands:
        print(
            "ERROR: 'commands' must be a non-empty list or non-empty scalar block.",
            file=sys.stderr,
        )
        sys.exit(1)

    for index, command in enumerate(commands):
        if not isinstance(command, str) or not command.strip():
            print(
                f"ERROR: commands[{index}] must be a non-empty string command block.",
                file=sys.stderr,
            )
            sys.exit(1)

    return payload


def write_sourceable_script(commands: list[str], output_file: str) -> None:
    """Write validated shell command blocks to a sourceable script file."""
    output_path = Path(output_file)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, "w") as f:
        f.write("# Generated by processing-instructions-file-creator.py\n")
        f.write("# shellcheck shell=bash\n\n")
        for command in commands:
            f.write(command.rstrip())
            f.write("\n\n")

    print(f"Generated {output_path}")


def main() -> None:
    input_file = os.getenv(
        "PROCESSING_INPUT_FILE", "/etc/config-in/processing-instructions.yaml"
    )
    output_file = os.getenv(
        "PROCESSING_OUTPUT_FILE", "/etc/config-out/processing-instructions.sh"
    )

    payload = load_instructions(input_file)
    write_sourceable_script(payload["commands"], output_file)

    print("Processing instructions rendering completed successfully.")


if __name__ == "__main__":
    main()
