---
apiVersion: v1
kind: ConfigMap
metadata:
  name: assign-science-review-flags-config
  labels:
    workflows.argoproj.io/configmap-type: Parameter
data:
  log_level: "DEBUG"
  # Git configuration.
  git_secret_name: "git-data-processing-metadata-key"
  git_secret_key: "ssh-private-key"
  git_repo_url: "git@github.com:BattelleEcology/data-processing-metadata.git"
  git_branch: "main"
  git_repo_dir: "science-review-flags"
  # Bucket for saving manifests.
  output_bucket: "neon-dev-argo-workflow-test"
  output_bucket_prefix: "assign_science_review_flags"
  # Path index for the source ID in the assignment output paths.
  source_id_path_index: "7"
  # R code
  relative_path_index: "3"
  parallelization_internal: "4"
  assignment_image: "us-central1-docker.pkg.dev/neon-shared-service/neonscience/neon-is-srf-asgn:v1.2.0"
  r_args_by_group.json: |
    {
      "default": "DirIn=$DIR_IN DirOut=$DIR_OUT DirErr=$ERR_PATH DateBgn=$DATE_BEGIN DateEnd=$DATE_END",
      "additions": {
      }
    }