##############################################################################################
#' @title Test of wrap.precip.aepg.smooth.R which is wrapper function

#' @title Compute precipitation from collector depths reported by the Belfort AEPG 600m
#' precipitation collector

#' @description Wrapper function. Aggregate and smooth strain gauge depth data reported by the
#' Belfort AEPG 600m weighing gauge sensor, and compute precipitation. Uncertainty estimates
#' are produced via a Monte Carlo approach using IAAFT surrogate data.

#' @param DirIn Character value. The input path to the data from a single source ID, structured as follows:
#' #/pfs/BASE_REPO/#/yyyy/mm/dd/#/location-id, where # indicates any number of parent and child directories
#' of any name, so long as they are not 'pfs' or recognizable as the 'yyyy/mm/dd' structure which indicates
#' the 4-digit year, 2-digit month, and' 2-digit day. The location-id is the unique identifier of the location. \cr
#'
#' Nested within this path are (at a minimum) the folders:
#'         /data
#'         /flags
#'         /threshold
#' The data folder holds a multiple data files with strain gauge depth data, one file per day,
#' from the same sensor/location. The daily files should be sequential such that they comprise a dataset
#' from the same sensor/location over a window of several days around 3 central processing days. The
#' window of time surrounding these days should be adequate such that edge effects in applying the
#' smoothing algorithm are minimal for the central days. The data files are named in the convention:
#' SOURCETYPE_LOCATIONID_YYYY-MM-DD.parquet
#'
#' The flags folder holds two files containing basic plausibility and calibration quality flags for
#' the central processing day only. These files should respectively be named in the convention:
#' SOURCETYPE_LOCATIONID_YYYY-MM-DD_flagsPlausibility.parquet
#' SOURCETYPE_LOCATIONID_YYYY-MM-DD_flagsCal.parquet
#' All other files in this directory will be ignored.
#'
#' The threshold folder contains a single file named thresholds.json that holds threshold parameters
#' applicable to the smoothing algorithm.
#'
#' @param DirOutBase Character value. The output path that will replace the #/pfs/BASE_REPO portion of DirIn.
#'
#' @param SchmStatHour (Optional). A json-formatted character string containing the schema for the hourly
#' output precipitation statistics and quality flags generated by this algorithm. May be NULL (default),
#' in which case the variable names will be automatically determined.
#' ENSURE THAT ANY PROVIDED OUTPUT SCHEMA MATCHES THE ORDER OF THE OUTPUT. Otherwise, outputs will be
#' labeled incorrectly. Best practice is to run the code without any schema first to understand the ordering
#' of the outputs, then relabel them as desired by providing a schema.

#' @param SchmStatDay (Optional). A json-formatted character string containing the schema for the daily
#' output precipitation statistics and quality flags. May be NULL (default),
#' in which case the  the variable names will be automatically determined.
#' ENSURE THAT ANY PROVIDED OUTPUT SCHEMA MATCHES THE ORDER OF THE OUTPUT.Otherwise, outputs will be
#' labeled incorrectly. Best practice is to run the code without any schema first to understand the ordering
#' of the outputs, then relabel them as desired by providing a schema.

#' @param SchmQfGage (Optional). A json-formatted character string containing the schema for the aggregated
#' strain gauge flags. May be NULL (default),
#' in which case the  the variable names will be automatically determined.
#' ENSURE THAT ANY PROVIDED OUTPUT SCHEMA MATCHES THE ORDER OF THE OUTPUT. Otherwise, outputs will be
#' labeled incorrectly. Best practice is to run the code without any schema first to understand the ordering
#' of the outputs, then relabel them as desired by providing a schema.

#' @param DirSubCopy (optional) Character vector. The names of additional subfolders at
#' the same level as the data/flags/threshold folders in the input path that are to be copied with a
#' symbolic link to the output path (i.e. carried through as-is). Note that the 'stats' and 'flags' directories
#' are automatically populated in the output and cannot be included here.

#' @param log A logger object as produced by NEONprocIS.base::def.log.init to produce structured log
#' output. Defaults to NULL, in which the logger will be created and used within the function. See NEONprocIS.base::def.log.init
#' for more details.
#'
#' @return A repository in DirOutBase containing the precipitation and uncertainty estimates along with
#' quality flags (incl. the final quality flag) produced by the depth smoothing algorithm, where DirOutBase
#' replaces BASE_REPO of argument \code{DirIn} but otherwise retains the child directory structure of the
#' input path. The terminal directories for each datum include, at a minimum, 'stats' and 'flags'. The stats folder
#' contains hourly and daily output for 3 data days centered on the day indicated in the path structure, one
#' file per day and output frequency (i.e. 6 total files), named appropriately. The output in the stats folder
#' contains the precipitation sum, uncertainty estimates, quality flags specific to the smoothing algorithm,
#' and final quality flag. The 'flags' folder will contain the plausibility and calibration flags aggregated
#' across the 3 strain gauges at the original measurement frequency for later processing into quality metrics.
#'
#' @references
#' License: (example) GNU AFFERO GENERAL PUBLIC LICENSE Version 3, 19 November 2007

#' @keywords Currently none

#' @examples
#' # NOT RUN
#' DirIn <- 'pfs/pW_thresh_select_ts_pad/2024/12/09/precip-weighing_YELL900000/aepg600m_heated/CFGLOC113591'
#' DirOutBase <- 'pfs/out'
#' wrap.precip.aepg.smooth(DirIn,DirOutBase,FileSchmL0)

#' @seealso Currently none

# changelog
#   Mija Choi (2025-01-15)
#     Initial creation
##############################################################################################
# Define test context
context("\n                       Unit test of wrap.precip.aepg.smooth.R\n")

# Unit test of wrap.precip.aepg.smooth.R
test_that("Unit test of wrap.precip.aepg.smooth.R", {
  source('../../flow.precip.aepg.smooth/wrap.precip.aepg.smooth.R')
  source('../../flow.precip.aepg.smooth/def.precip.depth.smooth.R')
  source('../../flow.precip.aepg.smooth/def.ucrt.agr.precip.bench.R')
  library(stringr)
  library(jsonlite)
  library(rjson)
  #
  testOutputBase = "pfs/out"
  testInputDir <-
    'pfs/pW_thresh_select_ts_pad_smoother/2024/11/08/pw_BLUE900000/aepg600m_heated/CFGLOC103882'
  
  # Test 1. A happy path
  
  dirParts <- NEONprocIS.base::def.dir.splt.pach.time(testInputDir)
  testOutputDir <- paste0(testOutputBase, dirParts$dirRepo)
  
  if (dir.exists(testOutputBase)) {
    unlink(testOutputBase, recursive = TRUE)
  }
  
  returnedOutputDir <-
    wrap.precip.aepg.smooth(DirIn = testInputDir, DirOutBase = testOutputBase)
  
  testOutputStatsDir <- paste0(testOutputDir, '/stats')
  testOutputFlagsDir <- paste0(testOutputDir, '/flags')
  testthat::expect_true(file.exists(testOutputStatsDir, recursive = TRUE))
  testthat::expect_true(file.exists(testOutputFlagsDir, recursive = TRUE))
  
  if (dir.exists(testOutputBase)) {
    unlink(testOutputBase, recursive = TRUE)
  }
  
  returnedOutputDir <-
    wrap.precip.aepg.smooth(DirIn = testInputDir, DirOutBase = testOutputBase)
  
  # Test 2. No manifest file, the output directories are created, but there will be no files in them due to the error.
  
  testInputDirnoManifest <-
    'pfs/pW_thresh_select_ts_pad_smoother/2024/10/01/pw_OSBS900000/aepg600m_noManifest/CFGLOC102875'
  
  dirParts <-
    NEONprocIS.base::def.dir.splt.pach.time(testInputDirnoManifest)
  testOutputDir <- paste0(testOutputBase, '/', dirParts$dirRepo)
  
  if (dir.exists(testOutputBase)) {
    unlink(testOutputBase, recursive = TRUE)
  }
  
  returnedOutputDir <-
    wrap.precip.aepg.smooth(DirIn = testInputDirnoManifest, DirOutBase = testOutputBase)
  
  testOutputStatsDir <- paste0(testOutputDir, '/stats')
  testOutputFlagsDir <- paste0(testOutputDir, '/flags')
  
  testthat::expect_true(dir.exists(testOutputStatsDir) ||
                          list.files(testOutputStatsDir) == 0)
  testthat::expect_true(dir.exists(testOutputFlagsDir) ||
                          list.files(testOutputFlagsDir) == 0)
  
  # Test 3. When more than 1 thresholds.json, only the first one will be taken with the info
  # "There is more than one threshold file...".
  
  testInputDir2thresholds <-
    'pfs/pW_thresh_select_ts_pad_smoother/2024/10/01/pw_OSBS900000/aepg600m_2thresholds/CFGLOC102875'
  
  dirParts <-
    NEONprocIS.base::def.dir.splt.pach.time(testInputDir2thresholds)
  testOutputDir <- paste0(testOutputBase, '/', dirParts$dirRepo)
  
  if (dir.exists(testOutputBase)) {
    unlink(testOutputBase, recursive = TRUE)
  }
  
  returnedOutputDir <-
    wrap.precip.aepg.smooth(DirIn = testInputDir2thresholds, DirOutBase = testOutputBase)
  
  testOutputStatsDir <- paste0(testOutputDir, '/stats')
  testOutputFlagsDir <- paste0(testOutputDir, '/flags')
  
  testthat::expect_true(dir.exists(testOutputStatsDir) ||
                          list.files(testOutputStatsDir) == 0)
  testthat::expect_true(dir.exists(testOutputFlagsDir) ||
                          list.files(testOutputFlagsDir) == 0)
  
  # Test 4. When not all files listed in the manifest.txt are in data directory
  # manifest.txt covers from 2024-09-27 to 2024-10-02
  # files in the data directory from 2024-09-30 to 2024-10-02
  # the output directories are created, but there will be no files in them with the wrarning message below:
  # "Timeseries pad incomplete. Missing the following days: 2024-09-27, 2024-09-28, 2024-09-29"
  
  testInputDirmissingDates <-
    'pfs/pW_thresh_select_ts_pad_smoother/2024/10/01/pw_OSBS900000/aepg600m_missingDates/CFGLOC102875'
  
  dirParts <-
    NEONprocIS.base::def.dir.splt.pach.time(testInputDirmissingDates)
  testOutputDir <- paste0(testOutputBase, '/', dirParts$dirRepo)
  
  if (dir.exists(testOutputBase)) {
    unlink(testOutputBase, recursive = TRUE)
  }
  
  returnedOutputDir <-
    wrap.precip.aepg.smooth(DirIn = testInputDirmissingDates, DirOutBase = testOutputBase)
  
  testOutputStatsDir <- paste0(testOutputDir, '/stats')
  testOutputFlagsDir <- paste0(testOutputDir, '/flags')
  
  testthat::expect_true(dir.exists(testOutputStatsDir) ||
                          list.files(testOutputStatsDir) == 0)
  testthat::expect_true(dir.exists(testOutputFlagsDir) ||
                          list.files(testOutputFlagsDir) == 0)
  
  
  # Test 5. When a term, precipBulk, is missing in thresholds.json
  
  testInputDirbadthresholds <-
    'pfs/pW_thresh_select_ts_pad_smoother/2024/10/01/pw_OSBS900000/aepg600m_badthresholds/CFGLOC102875'
  
  dirParts <-
    NEONprocIS.base::def.dir.splt.pach.time(testInputDirbadthresholds)
  testOutputDir <- paste0(testOutputBase, '/', dirParts$dirRepo)
  
  if (dir.exists(testOutputBase)) {
    unlink(testOutputBase, recursive = TRUE)
  }
  
  returnedOutputDir <-
    try(wrap.precip.aepg.smooth(DirIn = testInputDirbadthresholds, DirOutBase = testOutputBase),
        silent = TRUE)
  
  # Test 6. DirSubCopy not Null, for example, DirSubCopy = 'aaa'.
  # The input will be read from the DirSubCopy, but the output directory will be the same as in DirSubCopy = NULL
  if (dir.exists(testOutputBase)) {
    unlink(testOutputBase, recursive = TRUE)
  }
  
  DirSub = 'aaa'
  testInputDir <-
    'pfs/pW_thresh_select_ts_pad_smoother/2024/11/08/pw_BLUE900000/aepg600m_heated/CFGLOC103882'
  dirParts <- NEONprocIS.base::def.dir.splt.pach.time(testInputDir)
  testOutputDir <- paste0(testOutputBase, '/', dirParts$dirRepo)
  
  returnedOutputDir <-
    wrap.precip.aepg.smooth(DirIn = testInputDir,
                            DirOutBase = testOutputBase,
                            DirSubCopy = DirSub)
  
  testOutputDirStats <- paste0(testOutputDir, '/stats')
  testOutputDirFlags <- paste0(testOutputDir, '/flags')
  testthat::expect_true(file.exists(testOutputDirStats, recursive = TRUE))
  testthat::expect_true(file.exists(testOutputDirFlags, recursive = TRUE))
  #
})