##############################################################################################
#' @title Test of wrap.precip.aepg.smooth.R which is wrapper function

#' @title Compute precipitation from collector depths reported by the Belfort AEPG 600m 
#' precipitation collector 

#' @description Wrapper function. Aggregate and smooth strain gauge depth data reported by the 
#' Belfort AEPG 600m weighing gauge sensor, and compute precipitation. Uncertainty estimates
#' are produced via a Monte Carlo approach using IAAFT surrogate data. 

#' @param DirIn Character value. The input path to the data from a single source ID, structured as follows: 
#' #/pfs/BASE_REPO/#/yyyy/mm/dd/#/location-id, where # indicates any number of parent and child directories 
#' of any name, so long as they are not 'pfs' or recognizable as the 'yyyy/mm/dd' structure which indicates 
#' the 4-digit year, 2-digit month, and' 2-digit day. The location-id is the unique identifier of the location. \cr
#'
#' Nested within this path are (at a minimum) the folders:
#'         /data
#'         /flags
#'         /threshold
#' The data folder holds a multiple data files with strain gauge depth data, one file per day, 
#' from the same sensor/location. The daily files should be sequential such that they comprise a dataset
#' from the same sensor/location over a window of several days around 3 central processing days. The
#' window of time surrounding these days should be adequate such that edge effects in applying the 
#' smoothing algorithm are minimal for the central days. The data files are named in the convention:
#' SOURCETYPE_LOCATIONID_YYYY-MM-DD.parquet
#' 
#' The flags folder holds two files containing basic plausibility and calibration quality flags for 
#' the central processing day only. These files should respectively be named in the convention:
#' SOURCETYPE_LOCATIONID_YYYY-MM-DD_flagsPlausibility.parquet
#' SOURCETYPE_LOCATIONID_YYYY-MM-DD_flagsCal.parquet
#' All other files in this directory will be ignored.
#'
#' The threshold folder contains a single file named thresholds.json that holds threshold parameters
#' applicable to the smoothing algorithm. 
#'
#' @param DirOutBase Character value. The output path that will replace the #/pfs/BASE_REPO portion of DirIn. 
#'
#' @param SchmStatHour (Optional). A json-formatted character string containing the schema for the hourly 
#' output precipitation statistics and quality flags generated by this algorithm. May be NULL (default), 
#' in which case the variable names will be automatically determined.  
#' ENSURE THAT ANY PROVIDED OUTPUT SCHEMA MATCHES THE ORDER OF THE OUTPUT. Otherwise, outputs will be 
#' labeled incorrectly. Best practice is to run the code without any schema first to understand the ordering
#' of the outputs, then relabel them as desired by providing a schema.

#' @param SchmStatDay (Optional). A json-formatted character string containing the schema for the daily 
#' output precipitation statistics and quality flags. May be NULL (default), 
#' in which case the  the variable names will be automatically determined.  
#' ENSURE THAT ANY PROVIDED OUTPUT SCHEMA MATCHES THE ORDER OF THE OUTPUT.Otherwise, outputs will be 
#' labeled incorrectly. Best practice is to run the code without any schema first to understand the ordering
#' of the outputs, then relabel them as desired by providing a schema.

#' @param SchmQfGage (Optional). A json-formatted character string containing the schema for the aggregated 
#' strain gauge flags. May be NULL (default), 
#' in which case the  the variable names will be automatically determined.  
#' ENSURE THAT ANY PROVIDED OUTPUT SCHEMA MATCHES THE ORDER OF THE OUTPUT. Otherwise, outputs will be 
#' labeled incorrectly. Best practice is to run the code without any schema first to understand the ordering
#' of the outputs, then relabel them as desired by providing a schema.

#' @param DirSubCopy (optional) Character vector. The names of additional subfolders at 
#' the same level as the data/flags/threshold folders in the input path that are to be copied with a 
#' symbolic link to the output path (i.e. carried through as-is). Note that the 'stats' and 'flags' directories 
#' are automatically populated in the output and cannot be included here.

#' @param log A logger object as produced by NEONprocIS.base::def.log.init to produce structured log
#' output. Defaults to NULL, in which the logger will be created and used within the function. See NEONprocIS.base::def.log.init
#' for more details.
#'
#' @return A repository in DirOutBase containing the precipitation and uncertainty estimates along with 
#' quality flags (incl. the final quality flag) produced by the depth smoothing algorithm, where DirOutBase 
#' replaces BASE_REPO of argument \code{DirIn} but otherwise retains the child directory structure of the 
#' input path. The terminal directories for each datum include, at a minimum, 'stats' and 'flags'. The stats folder
#' contains hourly and daily output for 3 data days centered on the day indicated in the path structure, one 
#' file per day and output frequency (i.e. 6 total files), named appropriately. The output in the stats folder 
#' contains the precipitation sum, uncertainty estimates, quality flags specific to the smoothing algorithm, 
#' and final quality flag. The 'flags' folder will contain the plausibility and calibration flags aggregated
#' across the 3 strain gauges at the original measurement frequency for later processing into quality metrics.
#'
#' @references
#' License: (example) GNU AFFERO GENERAL PUBLIC LICENSE Version 3, 19 November 2007

#' @keywords Currently none

#' @examples 
#' # NOT RUN
#' DirIn <- 'pfs/pW_thresh_select_ts_pad/2024/12/09/precip-weighing_YELL900000/aepg600m_heated/CFGLOC113591'
#' DirOutBase <- 'pfs/out'
#' wrap.precip.aepg.smooth(DirIn,DirOutBase,FileSchmL0)

#' @seealso Currently none

# changelog 
#   Mija Choi (2025-01-15)
#     Initial creation
##############################################################################################
# Define test context
context("\n                       Unit test of wrap.precip.aepg.smooth.R\n")

# Unit test of wrap.precip.aepg.smooth.R
test_that("Unit test of wrap.precip.aepg.smooth.R", {
  source('../../flow.precip.aepg.smooth/wrap.precip.aepg.smooth.R')
  library(stringr)
  library(MFDFA)
  #
  testOutputBase = "pfs/out"
  testInputDir <-
    'pfs/pW_thresh_select_ts_pad/2024/12/09/precip-weighing_YELL900000/aepg600m_heated/CFGLOC113591'
  
  dirParts <- NEONprocIS.base::def.dir.splt.pach.time(testInputDir)
  testOutputDir <- paste0(testOutputBase, dirParts$dirRepo)
  
  #
  # Test 1. DirSubCopy is Null
  
  if (dir.exists(testOutputBase)) {
    unlink(testOutputBase, recursive = TRUE)
  }
  
  returnedOutputDir <-
    wrap.precip.aepg.smooth(DirIn = testInputDir, DirOutBase = testOutputBase)
  
#  testOutputStatsDir <- paste0(testOutputDir, '/stats')
  testthat::expect_true(file.exists( testOutputDir, recursive = TRUE))
  
  # Test 2. DirSubCopy not Null, for example, DirSubCopy = 'aaa'. 
  # The input files are copied over under DirSubCopy along with the output. So, 
  # pfs/out/2024/12/09/precip-weighing_YELL900000/aepg600m_heated/CFGLOC113591/ will have DirSubCopy, 'aaa', and the output directory, stats 
  # pfs/out/2024/12/09/precip-weighing_YELL900000/aepg600m_heated/CFGLOC113591/aaa/ will have stats and flags, copied from the input directory, 
  # pfs/pW_thresh_select_ts_pad/2024/12/09/precip-weighing_YELL900000/aepg600m_heated/CFGLOC113591/
  
  if (dir.exists(testOutputBase)) {
    unlink(testOutputBase, recursive = TRUE)
  }
  
  testInputDir <-
    'pfs/pW_thresh_select_ts_pad/2024/12/09/precip-weighing_YELL900000/aepg600m_heated/CFGLOC113591'
  DirSub = 'aaa'
  
  returnedOutputDir <-
    wrap.precip.aepg.smooth(DirIn = testInputDir,
                          DirOutBase = testOutputBase,
                          DirSubCopy = DirSub)
  
  testOutputCopyDirSub <- paste0(testOutputDir, '/aaa')
  # testOutputCopyDirSubStats <- paste0(testOutputCopyDirSub, '/stats')
  # testOutputCopyDirSubFlags <- paste0(testOutputCopyDirSub, '/flags') 
  testthat::expect_true(file.exists(testOutputCopyDirSub, recursive = TRUE))
  # testthat::expect_true(file.exists(testOutputCopyDirSubStats, recursive = TRUE))
  # testthat::expect_true(file.exists(testOutputCopyDirSubFlags, recursive = TRUE))
  
})