##############################################################################################
#' @title Unit test for insufficient data quality flag wrapper (wrap.qf.insuff.data)
#'
#' @author Nora Catolico
#'
#' @description Unit test for wrap.qf.insuff.data.R. This test covers:
#'      - Successful application of insufficient data QF on appropriate files
#'      - Creation of output directories and files
#'      - Pass-through of symbolic links for subdirectories
#'      - Error handling for missing files/columns
#'
#' @param InssuffParam Data table of parameters generated by flow script.
#' 
#' @param DirOut Character value. The base file path for the output data. 
#' 
#' @param SchmStats (optional), A json-formatted character string containing the schema for the output averaged stats parquet.
#' Should be the same as the input. 
#' 
#' @param SchmQMs (optional), A json-formatted character string containing the schema for the output quality metrics parquet 
#' with insufficient data quality flag added. 
#' 
#' @param DirSubCopy (optional) Character vector. The names of additional subfolders at 
#' the same level as the location folder in the input path that are to be copied with a symbolic link to the 
#' output path (i.e. not combined but carried through as-is).
#' 
#' @param log A logger object as produced by NEONprocIS.base::def.log.init to produce structured log
#' output. Defaults to NULL, in which the logger will be created and used within the function. See NEONprocIS.base::def.log.init
#' for more details.
#'
# changelog and author contributions
#   ncatolico (2026-02-09)
#     Original Creation
##############################################################################################
context("\n       | Unit test of Insufficient Data QF Wrapper for NEON IS data processing \n")

test_that("Unit test of wrap.qf.insuff.data.R", {
  source('../../flow.qf.insuff.data/wrap.qf.insuff.data.R')
  library(stringr)
  
  log <- NEONprocIS.base::def.log.init(Lvl = "debug")
  
  # Setup example test parameters
  DirIn <- "pfs/nitrate_insuff_data_in/2019/11/18/nitrate-surfacewater_POSE102100/sunav2/CFGLOC101686"
  DirOutBase <- "pfs/nitrate_out"
  SchmQM <- base::paste0(base::readLines('pfs/sunav2_avro_schemas/nitrate/nitrate_insufficient_data.avsc'), collapse = '')
  
  # Clean up output directory before test
  if (dir.exists(DirOutBase)) {
    unlink(DirOutBase, recursive = TRUE)
  }
  
  # Example insuffParam dataframe
  # Should match what your flow scripts produce (InfoSet, field, value, etc)
  insuffParam <- data.frame(
    InfoSet = c("insuffInfo1", "insuffInfo1", "insuffInfo1"),
    field = c("wndw", "minPoints", "term"),
    value = c("015", "5", "nitrate"),
    stringsAsFactors = FALSE
  )
  
  
  # Test 1: Successful run (correct input files/columns exist)
  wrap.qf.insuff.data(
    DirIn = DirIn,
    insuffParam = insuffParam,
    DirOutBase = DirOutBase,
    SchmQMs = SchmQM,
    DirSubCopy = NULL
  )
  
  # Check for output stats and QM files in expected locations
  InfoDirIn <- NEONprocIS.base::def.dir.splt.pach.time(DirIn)
  DirOutStats <- base::paste0(DirOutBase, InfoDirIn$dirRepo, "/stats")
  DirOutQMs <- base::paste0(DirOutBase, InfoDirIn$dirRepo, "/quality_metrics")
  statsFileNames <- base::list.files(DirOutStats, full.names = TRUE)
  qmFileNames <- base::list.files(DirOutQMs, full.names = TRUE)
  
  testthat::expect_true(length(statsFileNames) > 0)
  testthat::expect_true(length(qmFileNames) > 0)
  
  # Check that the insufficientDataQF and finalQF columns are correctly applied
  qmData <- NEONprocIS.base::def.read.parq(NameFile = qmFileNames[1])
  testthat::expect_true("insufficientDataQF" %in% names(qmData))
  testthat::expect_true("finalQF" %in% names(qmData))
  testthat::expect_true(all(qmData$finalQF == qmData$insufficientDataQF)) # FinalQF = InsuffQF
  
  # Clean up
  if (dir.exists(DirOutBase)) {
    unlink(DirOutStats, recursive = TRUE)
    unlink(DirOutQMs, recursive = TRUE)
    unlink(DirOutBase, recursive = TRUE)
  }
  
  # Test 2: Error if required columns missing in stats/QM
  insuffParam_bad <- data.frame(
    InfoSet = c("insuffInfo1", "insuffInfo1", "insuffInfo1"),
    field = c("wndw", "minPoints", "term"),
    value = c("015", "3", "INVALID_TERM"),
    stringsAsFactors = FALSE
  )
  returnedOutput <- try(wrap.qf.insuff.data(
    DirIn = DirIn,
    insuffParam = insuffParam_bad,
    DirOutBase = DirOutBase
  ),silent=TRUE)
  
  testthat::expect_true("try-error" %in% class(returnedOutput))
  
  # Clean up
  if (dir.exists(DirOutBase)) {
    unlink(DirOutStats, recursive = TRUE)
    unlink(DirOutQMs, recursive = TRUE)
    unlink(DirOutBase, recursive = TRUE)
  }
  
  
  # Test 3: Error if bad wndw format
  insuffParam_bad <- data.frame(
    InfoSet = c("insuffInfo1", "insuffInfo1", "insuffInfo1"),
    field = c("wndw", "minPoints", "term"),
    value = c("15min", "3", "nitrate"),
    stringsAsFactors = FALSE
  )
  returnedOutput <- try(wrap.qf.insuff.data(
    DirIn = DirIn,
    insuffParam = insuffParam_bad,
    DirOutBase = DirOutBase
    ),silent=TRUE)
  
  testthat::expect_true("try-error" %in% class(returnedOutput))
  
  # Clean up
  if (dir.exists(DirOutBase)) {
    unlink(DirOutBase, recursive = TRUE)
  }
  
})
