# Dockerfile for NEON IS Data Processing - fDOM Temperature and Absorbance Corrections for Water Quality

# Start with the neon-is-base-r image. 
FROM quay.io/battelleecology/neon-is-base-r:v0.0.29

# maintainer handle
MAINTAINER "Kaelin Cawley" kcawley@battelleecology.org

# Copy in calibration workflow
COPY ./flow.corr.wq.fdom.R /flow.corr.wq.fdom.R
