---
apiVersion: v1
kind: ConfigMap
metadata:
  name: location-asset-assignment-config-test
  labels:
    workflows.argoproj.io/configmap-type: Parameter
data:
  "config": |
    [
      {
        "key": "cmp22",
        "value": "DirIn=$DIR_IN DirOut=$DIR_OUT DirErr=$ERR_PATH FileYear=$FILE_YEAR TypeFile=asset 'Prop=HOR|VER|install_date|remove_date|name|site|Data Rate|locations|location_properties:LatTow|location_properties:LonTow'"
      }
    ]