# Dockerfile for NEON IS Data Processing - Threshold filtering by term and/or context

# Start with the neon-is-pack-qaqc-r image. 
FROM quay.io/battelleecology/neon-is-pack-qaqc-r:v0.0.7

# maintainer handle
MAINTAINER "Cove Sturtevant" csturtevant@battelleecology.org

# Copy in workflow
COPY ./flow.thsh.filt.R /flow.thsh.filt.R


