# Environment variables for the aepg600m calibration group and convert module
# To load this configmap in kubernetes:
#   kubectl config set-context --current --namespace=argo-workflows-dev
#   kubectl apply -f <configmapFile> 
# To delete it:
#   kubectl delete configmap <configmap name>
apiVersion: v1
kind: ConfigMap
metadata:
  name: aepg600m-cal-group-convert-config
  namespace: argo-workflows-dev
  labels:
    # Note: This label is required for the informer to detect this ConfigMap.
    workflows.argoproj.io/configmap-type: Parameter
data:
  # Workflow-level parameters
  log-level: INFO
  err-path: /pfs/errored_datums # All modules that produce errored datums
  schema-repo-eng-url: git@github.com:BattelleEcology/neon-avro-schemas.git
  schema-repo-eng-revision: develop # Branch or tag
  schema-repo-sci-url: https://github.com/NEONScience/NEON-IS-avro-schemas.git
  schema-repo-sci-revision: master # Branch or tag
  parallelism-internal: "3" # Internal R parallelization for all R modules
  
  # Parameters for input data load
  l0-bucket-name: neon-dev-l0-ingest
  l0-bucket-version-path: v2
  cal-bucket-name: neon-dev-argo-workflow-test # Assigned calibrations
  cal-bucket-prefix: aepg600m_calibration_assignment # Assigned calibrations
  source-type-index: "0" # Index in the manifest path  (must be present)
  year-index: "1" # Index in the manifest path (doesn't actually need to be present)
  month-index: "2" # Index in the manifest path (doesn't actually need to be present)
  day-index: "3" # Index in the manifest path (doesn't actually need to be present)
  source-id-index: "4" # Index in the manifest path (doesn't actually need to be present)
  out-path-l0: /inputs/DATA_PATH_ARCHIVE
  out-path-cal: /inputs/CALIBRATION_PATH
  
 # Parameters for filter-joiner merging calibrations with data
  filter-joiner-config: |
    ---
    # Configuration for filter-joiner module that will bring together the data and calibrations
    # In Pachyderm root will be index 0, 'pfs' index 1, and the repo name index 2.
    # Metadata indices will typically begin at index 3.
    input_paths:
    - path:
        name: DATA_PATH_ARCHIVE
        # Filter for data directory
        glob_pattern: /inputs/DATA_PATH_ARCHIVE/aepg600m/*/*/*/*/**
        # Join on named location (already joined below by day)
        join_indices: [7]
        outer_join: true
    - path:
        name: CALIBRATION_PATH
        # Filter for data directory
        glob_pattern: /inputs/CALIBRATION_PATH/aepg600m/*/*/*/*/**
        # Join on named location (already joined below by day)
        join_indices: [7]
        outer_join: true
  relative-path-index: "3"
  link-type: SYMLINK
  out-path-joiner: /pfs/data_cal_joined

  # Command line arguments and other input params for flow.kfka.comb.R
  kfka-comb-r-args: >
    DirIn=$OUT_PATH_JOINER
    DirOut=$OUT_PATH_KAFKA_COMB
    DirErr=$ERR_PATH
    FileSchmL0=/inputs/schemas-eng/schemas/aepg600m/aepg600m.avsc
    DirSubCopy=calibration
  out-path-kafka-comb: /pfs/kafka_combined

  # Command line arguments and other input params for flow.cal.conv.R
  cal-conv-r-args: >
    DirIn=$OUT_PATH_KAFKA_COMB
    DirOut=$OUT_PATH_CAL_CONV
    DirErr=$ERR_PATH
    FileSchmData=/inputs/schemas-sci/avro_schemas/aepg600m/aepg600m_calibrated.avsc
    FileSchmQf=/inputs/schemas-sci/avro_schemas/aepg600m/flags_calibration_aepg600m.avsc
    ConvFuncTerm1=def.cal.conv.poly.aepg600m:strain_gauge1_frequency_raw \
    ConvFuncTerm2=def.cal.conv.poly.aepg600m:strain_gauge2_frequency_raw \
    ConvFuncTerm3=def.cal.conv.poly.aepg600m:strain_gauge3_frequency_raw \
    "TermQf=strain_gauge1_frequency_raw|strain_gauge2_frequency_raw|strain_gauge3_frequency_raw" 
  out-path-cal-conv: /pfs/aepg600m_calibration_group_and_convert

  # Parameters for data upload to bucket
  output-bucket-name: neon-dev-argo-workflow-test
  output-bucket-prefix: aepg600m_calibration_group_and_convert # Output Repo name