# Dockerfile for NEON IS Data Processing - Location Filter

# Start with the base image. 
FROM quay.io/battelleecology/neon-is-base-r:v0.0.23

# maintainer handle
MAINTAINER "Cove Sturtevant" csturtevant@battelleecology.org

# Copy in calibration filter workflow
COPY ./flow.loc.filt.R /flow.loc.filt.R
