---
pipeline:
  name: nitrate_os_table_loader
transform:
  image: us-central1-docker.pkg.dev/neon-shared-service/neonscience/neon-is-os-table-loader:sha-98d1c1e
  cmd:
  - /bin/bash
  stdin:
  - '#!/bin/bash'
  - python3 -m os_table_loader.main
  env:
    # File output options are 'csv' or 'parquet'. 
    FILE_TYPE: csv
    OUT_PATH: /pfs/out
    PARTIAL_TABLE_NAME: maintenance
    DB_CONFIG_SOURCE: mount
    LOG_LEVEL: DEBUG 
  secrets:
  - name: pdr-secret
    mount_path: /var/db_secret
input:
  pfs:
    name: IN_PATH 
    repo: nitrate_os_table_loader_control_tick
    glob: /*
autoscaling: true
resource_requests:
  memory: 1G
  cpu: 1.2
resource_limits:
  memory: 2G
  cpu: 2
sidecar_resource_requests:
  memory: 2G
  cpu: 0.5
datum_set_spec:
  number: 1
scheduling_spec:
  node_selector:
    cloud.google.com/compute-class: pach-pipeline-class
