# Dockerfile for NEON IS Data Processing - Quality metrics and final quality flag module

# Start with the base image. 
FROM quay.io/battelleecology/neon-is-pack-qaqc-r:v0.0.6

# maintainer handle
MAINTAINER "Cove Sturtevant" csturtevant@battelleecology.org

# Copy in calibration filter workflow
COPY ./flow.qaqc.qm.R /flow.qaqc.qm.R
