# Dockerfile for NEON IS Data Processing - Basic statistics module

# Start with the base image. 
FROM quay.io/battelleecology/neon-is-base-r:v0.0.29

# maintainer handle
MAINTAINER "Cove Sturtevant" csturtevant@battelleecology.org

# Copy in calibration filter workflow
COPY ./flow.stat.basc.R /flow.stat.basc.R
