---
# Workflow for assigning groups to data days.
# The data is loaded to a shared volume.
# The assignment module processes whatever is in the volume.
# The final output is written to a bucket.
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: assign-groups
spec:
  entrypoint: main
  volumes:
    # ConfigMap volumes for map-sources
    - name: source-volume
      configMap:
        name: groups-config
    - name: mapping-volume
      configMap:
        name: assign-groups-config
    - name: output-volume
      emptyDir: { }
  arguments:
    parameters:
      - name: run_date
        value: "{{=sprig.date('2006/01/02', workflow.creationTimestamp)}}"
      - name: date_begin
        value: "{{=sprig.date('2006-01-02', workflow.creationTimestamp)}}"
      - name: configuration
        value: assign-groups-config
  templates:
    - name: main
      steps:
        - - name: get-items
            templateRef:
              name: map-sources
              template: main
            arguments:
              parameters:
                - name: source_key
                  value: groups
                - name: mapping_key
                  value: r_args_by_group.json
        - - name: run-step
            templateRef:
              name: assign-locations-groups
              template: main
            arguments:
              parameters:
                - name: source_type
                  value: '{{item.key}}'
                - name: r_args
                  value: '{{item.value}}'
            withParam: '{{steps.get-items.outputs.parameters.items}}'