---
pipeline:
  name: aepg600m_ingest_days
transform:
  image: us-central1-docker.pkg.dev/neon-shared-service/neonscience/neon-is-gcs-data:sha-f2497a2
  env:
    SOURCE_TYPE_INDEX: "3"
    YEAR_INDEX: "4"
    MONTH_INDEX: "5"
    DAY_INDEX: "6"
  cmd:
  - sh
  - "-c"
  - |-
    /bin/bash <<'EOF'
    # Use bash-scrict mode. See http://redsymbol.net/articles/unofficial-bash-strict-mode/
    set -euo pipefail
    IFS=$'\n\t'
    
    if [[ -v INGEST_MANIFEST ]]; then
    
      echo "Ingest manifest: $INGEST_MANIFEST"
  
      # Split $INGEST_MANIFEST path into array
      IFS='/' read -r -a path_parts <<< "$INGEST_MANIFEST"
      
      # Extract elements of the datum path
      source_type="${path_parts[$SOURCE_TYPE_INDEX]}"
      ingest_year="${path_parts[$YEAR_INDEX]}"
      ingest_month="${path_parts[$MONTH_INDEX]}"
      ingest_day="${path_parts[$DAY_INDEX]}"
      
      # Form out base output path
      base_out_path="/pfs/out/${path_parts[$SOURCE_TYPE_INDEX]}"
      
      # Read the ingest manifest and distribute a manifest file to each date in the manifest
      for data_date in $(cat "$INGEST_MANIFEST" | jq -r '.[]'); do
  
          echo "Data date: $data_date"
          
          # Replace the dashes with forward slashes to make a date path
          data_date_path="${data_date//-//}"
          
          # Make a file at this path named for the manifest
          output_dir="${base_out_path}/${data_date_path}"
          output_file="${output_dir}/manifest_${ingest_year}-${ingest_month}-${ingest_day}.json"
          
          # Create directory path if it doesn't exist
          mkdir -p "$output_dir"
  
          # Create the JSON file with the data date inside
          echo -e "{\n  \"data_date\":\"$data_date\",\n  \"ingest_date\":\"${ingest_year}-${ingest_month}-${ingest_day}\"\n}" > "$output_file"
      done
      
    else
      
      # Write a cron tick file so we can use it later when we merge staging into master instead of a standalone cron input
      output_dir="/pfs/out/tick"
      tick_str=$(date -u +%Y-%m-%dT%H:%M:%SZ)
      output_file="${output_dir}/${tick_str}"
      mkdir -p "$output_dir"
      echo -e ${tick_str} > "$output_file"
      
    fi
    
    EOF
input:
  union:
  # Run on a cron as well so that we can create a cron trigger file for use in later modules
  - cron:
      name: tick
      # spec: "@every 2m"
      spec: "0 0 * * *" # Run at 00:00 GMT
      overwrite: true
  - pfs:
      name: INGEST_MANIFEST
      repo: aepg600m_ingest_trigger
      glob: /aepg600m/*/*/*/manifest.json
      branch: master
  - pfs:
      name: INGEST_MANIFEST
      repo: aepg600m_heated_ingest_trigger
      glob: /aepg600m_heated/*/*/*/manifest.json
      branch: master
output_branch: staging
resource_requests:
  memory: 500M
  cpu: 1.5
resource_limits:
  memory: 800M
  cpu: 1.5
sidecar_resource_requests:
  memory: 500M
  cpu: 0.2
autoscaling: true
scheduling_spec:
  node_selector:
    cloud.google.com/compute-class: pach-pipeline-class