# Dockerfile for NEON IS Data Processing - Dissolved Oxygen Expanded Uncertainty Calculations for Water Quality

# Start with the calibration package image. 
FROM quay.io/battelleecology/neon-is-pack-cal-r:v0.0.11

# maintainer handle
MAINTAINER "Kaelin Cawley" kcawley@battelleecology.org

# Copy in calibration workflow
COPY ./flow.unc.wq.do.R /flow.unc.wq.do.R
