# Dockerfile for NEON IS Data Processing - Restructure repo by location

# Start with the base image. 
FROM quay.io/battelleecology/neon-is-base-r:v0.0.28

# maintainer handle
MAINTAINER "Cove Sturtevant" csturtevant@battelleecology.org

# Copy in calibration filter workflow
COPY ./flow.loc.repo.strc.R /flow.loc.repo.strc.R
