##############################################################################################
#' @title Unit test of wrap.ucrt.dp0p.R,
#' wrapper for computing individual measurement uncertainty for calibrated data at native
#' frequency (NEON L0' data).

#' @description
#' Run unit tests for wrap.ucrt.dp0p.R. The input json for the test is ucrt-coef-fdas-input.json.
#' The tests include positive and negative scenarios.
#' The positive test is for a case when all the params to the function are valid
#' The negative tests are when a param(s) is empty or does not have invalid values

#' Refer to wrap.ucrt.dp0p.R for the details of the function.

#' @param data Data frame of L0 data. Must include POSIXct time variable readout_time.
#' @param ParaUcrt A data frame of the variables for which individual measurement uncertainty is
#' to be calculated. Columns include:\cr
#' \code{var} Character. The variable in data for which to compute uncertainty \cr
#' \code{typeFdas} A single character indicating the type of measurement made by NEON's field
#' data acquisision system (GRAPE). Acceptable values are "R" for resistance measurements, "V"
#' for voltage measurements, or NA (no quotes) for measurements in which FDAS uncertainty does
#' not apply (e.g. digital L0 output) \cr
#' \code{FuncUcrt} A character string indicating the individual measurement (calibration) uncertainty
#' function within the NEONprocIS.cal package that should be used. Note that this does not include
#' FDAS uncertainty. For most NEON data products, this will be "def.ucrt.meas.cnst". Note that any
#' alternative function must accept arguments "data", "infoCal", and "log", even if they are unused
#' in the function, and must return a data frame, one column of which is labeled "ucrtMeas" which
#' corresponds to the individual measurement uncertainty for the variable. Input "data" to the function
#' is an array of the data for the applicable term. Input "infoCal" is a data frame of calibration
#' information (including uncertainty) as returned from NEONprocIS.cal::def.read.cal.xml.
#' If no calibration files are associated with the term, infoCal would be passed in to the function as
#' NULL. Input "log" is a logger object as generated by NEONprocIS.base::def.log.init and used in
#' this script to generate hierarchical logging.\cr
#' @param ucrtCoefFdas A data frame of FDAS uncertainty coefficients, as read by
#' NEONprocIS.cal::def.read.ucrt.coef.fdas. Columns include:\cr
#' \code{Name} Character. Name of the coefficient.\cr
#' \code{Value} Character. Value of the coefficient.\cr
#' \code{.attrs} Character. Relevant attribute (i.e. units)\cr
#' Defaults to NULL, in which case no variables in ParaUcrt may indicate that FDAS uncertainty
#' applies.
#' @param calSlct A named list of data frames, list element corresponding to the variables in
#' ParaUcrt. The data frame in each list element holds information about the calibration files and
#' time periods that apply to the variable, as returned from NEONprocIS.cal::def.cal.slct.
#' See documentation for that function. Assign NULL to list elements (variables) for which calibration
#' information is not applicable (i.e. a function other than def.ucrt.meas.cnst is used to compute its
#' uncertainty).
#' @param DirCal Character string. Relative or absolute path (minus file name) to the main calibration
#' directory. Nested within this directory are directories for each variable in calSlct, each holding
#' calibration files for that variable. Defaults to "./"
#' @param mappNameVar A data frame with in/out variable name mapping as produced by
#' NEONprocIS.base::def.var.mapp.in.out. See documentation for that function. If input (default is NULL),
#' output variable names will be appended as prefixes to the column names in each output data frame.
#' @param log A logger object as produced by NEONprocIS.base::def.log.init to produce structured log
#' output. Defaults to NULL, in which the logger will be created and used within the function.

#' @return A named list, each element corresponding to those in ParaUcrt$var and holding a data
#' frame of uncertainty data. Note that each row in each data frame corresponds to the times in
#' data$readout_time, but the variable readout_time is not included in the output. One column
#' in each data frame is labeled ucrtComb, corresponding to the combined measurement uncertainty
#' of the individual measurements and FDAS (if applicable). If FDAS uncertainty does not apply,
#' ucrtComb is simply a copy of ucrtMeas. \cr

#' @references Currently none
#' License: (example) GNU AFFERO GENERAL PUBLIC LICENSE Version 3, 19 November 2007

#' @keywords Currently none

#' @examples Currently none

#' @seealso Currently none

#' @examples
#' To run with testthat:
#' devtools::test(pkg="<path>/NEON-IS-data-processing/pack/NEONprocIS.cal")
#' an example, devtools::test(pkg="C:/projects/NEON-IS-data-processing/pack/NEONprocIS.cal")

# changelog and author contributions / copyrights
#   Mija Choi (2020-08-05)
#     Original Creation
##############################################################################################
# Define test context
context("\n                       Unit test of def-cal-conv-poly-b.R\n")

# Unit test of def-cal-conv-poly-b.R
test_that("Unit test of def-cal-conv-poly-b.R", {
   testDir = "testdata/"
   
   testData = "L0_data.csv"
   testDataPath <- paste0(testDir, testData)
   
   data0 <- read.csv(testDataPath, sep = ",", header = TRUE)
   
   data <- data0$resistance
   
   # Happy path 1 - Check the CVALR1 coefficient in the calibration file. If it is present,
   # set the suspect calibration flag for all data values to the value of the coefficient
   # (1=bad,0=good).
   
   testFileCal = "calibration2.xml"
   testFileCalPath <- paste0(testDir, testFileCal)
   
   infoCal <- NEONprocIS.cal::def.read.cal.xml (testFileCalPath, Vrbs = TRUE)
   
   qfSusp <- NEONprocIS.cal::def.qf.cal.susp(data, infoCal)
   
   expect_true (all(qfSusp) == 0)
   
   # Happy path 2 -  If the CVALR1 coefficient is not present, set the suspect calibration flag
   # to 0.
   
   testFileCal = "calibration4.xml"
   testFileCalPath <- paste0(testDir, testFileCal)
   
   infoCal <- NEONprocIS.cal::def.read.cal.xml (testFileCalPath, Vrbs = TRUE)
   
   qfSusp <- NEONprocIS.cal::def.qf.cal.susp(data, infoCal)
   
   expect_true (all(qfSusp) == 0)
   
   # Happy path 3 - If no calibration information is available, set the flag to -1.
   
})
