apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-workflows-dev

resources:
  - ../../base
  - configmap-env.yaml
  - configmap-resource-request.yaml

patchesStrategicMerge:
  - |-
    apiVersion: argoproj.io/v1alpha1
    kind: WorkflowTemplate
    metadata:
      name: calibration-group-and-convert
    spec:
      arguments:
        parameters:
          - name: config-map-env-name
            value: aepg600m-heated-calibration-group-convert-env-config
          - name: config-map-resource-request-name
            value: aepg600m-heated-calibration-group-convert-resource-config

commonLabels:
  sensor: aepg600m_heated
  workflow: calibration-group-and-convert