apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-workflows-dev

resources:
  - ../../base/calibration-group-and-convert.yaml
  - configmap.yaml

# Patch the WorkflowTemplate to use aepg600m-specific ConfigMap name
patchesStrategicMerge:
  - |-
    apiVersion: argoproj.io/v1alpha1
    kind: WorkflowTemplate
    metadata:
      name: calibration-group-and-convert
    spec:
      arguments:
        parameters:
          - name: config-map-name
            value: aepg600m-calibration-group-convert-config

commonLabels:
  sensor: aepg600m
  workflow: calibration-group-and-convert
