apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-workflows-dev

resources:
  - ../../base/calibration-group-and-convert.yaml
  - ../../base/configmap-processing.yaml
  - configmap-parameters.yaml

# Patch the WorkflowTemplate to use cmp22-specific ConfigMap name
patchesStrategicMerge:
  - |-
    apiVersion: argoproj.io/v1alpha1
    kind: WorkflowTemplate
    metadata:
      name: calibration-group-and-convert
    spec:
      arguments:
        parameters:
          - name: config-map-parameter-name
            value: cmp22-calibration-group-convert-parameter-config
          - name: config-map-processing-name
            value: calibration-group-convert-processing-config

commonLabels:
  sensor: cmp22
  workflow: calibration-group-and-convert
