# Dockerfile for NEON IS Data Processing - Calibration Conversion

# Start with the calibration package image. 
FROM quay.io/battelleecology/neon-is-pack-cal-r:v0.0.11

# maintainer handle
MAINTAINER "Cove Sturtevant" csturtevant@battelleecology.org

# Copy in calibration workflow
COPY ./flow.cal.conv.R /flow.cal.conv.R
