library(devtools)
library(covr)
module_path <- Sys.getenv("MODULE_PATH")
module_name <- Sys.getenv("MODULE_NAME")
devtools::install(module_path)
devtools::test(pkg=module_path)
cov <- covr::package_coverage(path=module_path)
covr::to_cobertura(cov, filename=paste0(module_name, "-cobertura.xml"))