library(devtools)
library(covr)
devtools::install("./pack/NEONprocIS.base/")
devtools::test(pkg="./pack/NEONprocIS.base/")
cov <- covr::package_coverage(path="./pack/NEONprocIS.base/")
covr::report(cov, file="NEONprocIS.base-coverage.html")