library(devtools)
library(covr)
devtools::install("${{ env.MODULE_PATH }}")
devtools::test(pkg="${{ env.MODULE_PATH }}")
cov <- covr::package_coverage(path="${{ env.MODULE_PATH }}")
covr::report(cov, file="${{ env.MODULE_NAME }}-coverage.html")