---
pipeline:
  name: l4discharge_sdrc_stageDscCurve_table_loader_control 
transform:
  cmd: ["/bin/bash"]
input:
  cron:
    name: tick
    spec: "@never"
    overwrite: true
autoscaling: true
scheduling_spec:
  node_selector:
    cloud.google.com/compute-class: pach-pipeline-class
