from maintenance_table_loader.field_loader import Field
from maintenance_table_loader.table_loader import Table


def get_fields(_table: Table) -> list[Field]:
    """Mock function to return the maintenance table fields."""
    return [
        Field(field_id=17832, table_id=1550, rank=1, data_product_number=None, field_name='uid',
              description='Unique ID within NEON database; an identifier for the record', data_type_code='string',
              meas_scale='textDomain', ontology_mapping=None, pub_format='asIs',
              example_entry='W34P089AEJGAERTUERUI', field_type='uid', inputs=None, ingest_source_type='GENERATED',
              ingest_source_type_param=None, time_index=None, time_description=None, download_package='basic',
              data_category='N', sample_info=None, lov_code=None, primary_key='N', unit_name='NA',
              redaction_flag=None),
        Field(field_id=17833, table_id=1550, rank=2, data_product_number=None, field_name='startDate',
              description='The start date-time or interval during which an event occurred',
              data_type_code='dateTime', meas_scale='dateTime', ontology_mapping=None,
              pub_format="yyyy-MM-dd'T'HH:mm'Z'(floor)", example_entry='2016-06-12T13:30',
              field_type='resultStartDate', inputs='activityStartDate', ingest_source_type='ACTIVITY_TABLE',
              ingest_source_type_param=None, time_index=None, time_description=None, download_package='basic',
              data_category='N', sample_info=None, lov_code=None, primary_key='Y', unit_name='NA',
              redaction_flag=None),
        Field(field_id=17834, table_id=1550, rank=3, data_product_number=None, field_name='endDate',
              description='The end date-time or interval during which an event occurred', data_type_code='dateTime',
              meas_scale='dateTime', ontology_mapping=None, pub_format="yyyy-MM-dd'T'HH:mm'Z'(floor)",
              example_entry='2016-06-12T13:30', field_type='resultEndDate', inputs='activityEndDate',
              ingest_source_type='ACTIVITY_TABLE', ingest_source_type_param=None, time_index=None,
              time_description=None, download_package='basic', data_category='N', sample_info=None, lov_code=None,
              primary_key='N', unit_name='NA', redaction_flag=None),
        Field(field_id=17835, table_id=1550, rank=4, data_product_number=None, field_name='domainID',
              description='Unique identifier of the NEON domain', data_type_code='string', meas_scale='nominal',
              ontology_mapping=None, pub_format='asIs', example_entry='D02', field_type='DP', inputs='DOMAIN',
              ingest_source_type='NAMED_LOCATION', ingest_source_type_param=None, time_index=None,
              time_description=None, download_package='basic', data_category='N', sample_info=None, lov_code=None,
              primary_key='N', unit_name='NA', redaction_flag=None),
        Field(field_id=17836, table_id=1550, rank=5, data_product_number=None, field_name='siteID',
              description='NEON site code', data_type_code='string', meas_scale='nominal', ontology_mapping=None,
              pub_format='asIs', example_entry='ARIK', field_type='DP', inputs='SITE',
              ingest_source_type='NAMED_LOCATION', ingest_source_type_param=None, time_index=None,
              time_description=None, download_package='basic', data_category='N', sample_info=None, lov_code=None,
              primary_key='Y', unit_name='NA', redaction_flag=None),
        Field(field_id=17837, table_id=1550, rank=6, data_product_number=None, field_name='namedLocation',
              description='Name of the measurement location in the NEON database', data_type_code='string',
              meas_scale='nominal', ontology_mapping=None, pub_format='asIs',
              example_entry='SYCA.AOS.groundwater.well.001', field_type='DP', inputs='namedLocationName',
              ingest_source_type='ACTIVITY_TABLE', ingest_source_type_param=None, time_index=None,
              time_description=None, download_package='basic', data_category='N', sample_info=None, lov_code=None,
              primary_key='Y', unit_name='NA', redaction_flag=None),
        Field(field_id=17838, table_id=1550, rank=7, data_product_number=None, field_name='connectToTroll',
              description='Indicator of whether field staff physically connected to the troll',
              data_type_code='string', meas_scale='nominal', ontology_mapping=None, pub_format='LOV',
              example_entry='N', field_type='DP', inputs='connectToTroll', ingest_source_type='DP_TABLE',
              ingest_source_type_param=None, time_index=None, time_description=None, download_package='basic',
              data_category='N', sample_info=None, lov_code='Yes or No choice', primary_key='N', unit_name='NA',
              redaction_flag=None),
        Field(field_id=17839, table_id=1550, rank=8, data_product_number=None, field_name='trollSensorSwap',
              description='Indicator of whether troll sensor was swapped out', data_type_code='string',
              meas_scale='nominal', ontology_mapping=None, pub_format='LOV', example_entry='N', field_type='DP',
              inputs='trollSensorSwap', ingest_source_type='DP_TABLE', ingest_source_type_param=None,
              time_index=None, time_description=None, download_package='basic', data_category='N', sample_info=None,
              lov_code='Yes or No choice', primary_key='N', unit_name='NA', redaction_flag=None),
        Field(field_id=17840, table_id=1550, rank=9, data_product_number=None, field_name='gwWellSensorAssetTagID',
              description='Identifier for the asset tag on the groundwater well troll sensor',
              data_type_code='string', meas_scale='textDomain', ontology_mapping=None, pub_format='asIs',
              example_entry='30000000000000', field_type='DP', inputs='gwWellSensorAssetTagID',
              ingest_source_type='DP_TABLE', ingest_source_type_param=None, time_index=None, time_description=None,
              download_package='basic', data_category='N', sample_info=None, lov_code=None, primary_key='N',
              unit_name='NA', redaction_flag=None),
        Field(field_id=17841, table_id=1550, rank=10, data_product_number=None,
              field_name='internalBatteryLevelChecked',
              description='Indicator of whether the internal sensor battery was checked', data_type_code='string',
              meas_scale='nominal', ontology_mapping=None, pub_format='LOV', example_entry='N', field_type='DP',
              inputs='internalBatteryLevelChecked', ingest_source_type='DP_TABLE', ingest_source_type_param=None,
              time_index=None, time_description=None, download_package='basic', data_category='N', sample_info=None,
              lov_code='Yes or No choice', primary_key='N', unit_name='NA', redaction_flag=None),
        Field(field_id=17842, table_id=1550, rank=11, data_product_number=None, field_name='internalBatteryVoltage',
              description='Voltage of internal sensor battery', data_type_code='real', meas_scale='ratio',
              ontology_mapping=None, pub_format='*.#(round)', example_entry='3120', field_type='DP',
              inputs='internalBatteryVoltage', ingest_source_type='DP_TABLE', ingest_source_type_param=None,
              time_index=None, time_description=None, download_package='basic', data_category='N', sample_info=None,
              lov_code=None, primary_key='N', unit_name='millivolt', redaction_flag=None),
        Field(field_id=17843, table_id=1550, rank=12, data_product_number=None,
              field_name='internalBatteryPercentUsed', description='Percent of internal troll battery used',
              data_type_code='real', meas_scale='ratio', ontology_mapping=None, pub_format='integer',
              example_entry='23.00%', field_type='DP', inputs='internalBatteryPercentUsed',
              ingest_source_type='DP_TABLE', ingest_source_type_param=None, time_index=None, time_description=None,
              download_package='basic', data_category='N', sample_info=None, lov_code=None, primary_key='N',
              unit_name='percent', redaction_flag=None),
        Field(field_id=17844, table_id=1550, rank=13, data_product_number=None, field_name='externalBatteryAttached',
              description='Indicator of whether an external battery was attached', data_type_code='string',
              meas_scale='nominal', ontology_mapping=None, pub_format='LOV', example_entry='N', field_type='DP',
              inputs='externalBatteryAttached', ingest_source_type='DP_TABLE', ingest_source_type_param=None,
              time_index=None, time_description=None, download_package='basic', data_category='N', sample_info=None,
              lov_code='Yes or No choice', primary_key='N', unit_name='NA', redaction_flag=None),
        Field(field_id=17845, table_id=1550, rank=14, data_product_number=None, field_name='externalBatteryVoltage',
              description='Voltage of external sensor battery', data_type_code='real', meas_scale='ratio',
              ontology_mapping=None, pub_format='*.#(round)', example_entry='3120', field_type='DP',
              inputs='externalBatteryVoltage', ingest_source_type='DP_TABLE', ingest_source_type_param=None,
              time_index=None, time_description=None, download_package='basic', data_category='N', sample_info=None,
              lov_code=None, primary_key='N', unit_name='millivolt', redaction_flag=None),
        Field(field_id=17846, table_id=1550, rank=15, data_product_number=None, field_name='internalLogsDownloaded',
              description='Indicator of whether the troll data files were downloaded', data_type_code='string',
              meas_scale='nominal', ontology_mapping=None, pub_format='LOV', example_entry='N', field_type='DP',
              inputs='internalLogsDownloaded', ingest_source_type='DP_TABLE', ingest_source_type_param=None,
              time_index=None, time_description=None, download_package='basic', data_category='N', sample_info=None,
              lov_code='Yes or No choice', primary_key='N', unit_name='NA', redaction_flag=None),
        Field(field_id=17847, table_id=1550, rank=16, data_product_number=None,
              field_name='gwWellReplacementSensorAssetTagID',
              description='Identifier for the asset tag on a newly installed groundwater well troll sensor',
              data_type_code='string', meas_scale='textDomain', ontology_mapping=None, pub_format='asIs',
              example_entry='30000000000000', field_type='DP', inputs='gwWellReplacementSensorAssetTagID',
              ingest_source_type='DP_TABLE', ingest_source_type_param=None, time_index=None, time_description=None,
              download_package='basic', data_category='N', sample_info=None, lov_code=None, primary_key='N',
              unit_name='NA', redaction_flag=None),
        Field(field_id=17848, table_id=1550, rank=17, data_product_number=None,
              field_name='newTrollConfigurationVerified', description='Verification of new troll configuration',
              data_type_code='string', meas_scale='nominal', ontology_mapping=None, pub_format='LOV',
              example_entry='N', field_type='DP', inputs='newTrollConfigurationVerified',
              ingest_source_type='DP_TABLE', ingest_source_type_param=None, time_index=None, time_description=None,
              download_package='basic', data_category='N', sample_info=None, lov_code='Yes or No choice',
              primary_key='N', unit_name='NA', redaction_flag=None),
        Field(field_id=17849, table_id=1550, rank=18, data_product_number=None, field_name='loggingEnabled',
              description='Indicator of whether logging was enabled', data_type_code='string', meas_scale='nominal',
              ontology_mapping=None, pub_format='LOV', example_entry='N', field_type='DP', inputs='loggingEnabled',
              ingest_source_type='DP_TABLE', ingest_source_type_param=None, time_index=None, time_description=None,
              download_package='basic', data_category='N', sample_info=None, lov_code='Yes or No choice',
              primary_key='N', unit_name='NA', redaction_flag=None),
        Field(field_id=17850, table_id=1550, rank=19, data_product_number=None, field_name='trollDepthVerified',
              description='Indicator of whether depth of sensor remains unchanged', data_type_code='string',
              meas_scale='nominal', ontology_mapping=None, pub_format='LOV', example_entry='N', field_type='DP',
              inputs='trollDepthVerified', ingest_source_type='DP_TABLE', ingest_source_type_param=None,
              time_index=None, time_description=None, download_package='basic', data_category='N', sample_info=None,
              lov_code='Yes or No choice', primary_key='N', unit_name='NA', redaction_flag=None),
        Field(field_id=17851, table_id=1550, rank=20, data_product_number=None, field_name='gwWellDry',
              description='Indicator of whether groundwater well has no water', data_type_code='string',
              meas_scale='nominal', ontology_mapping=None, pub_format='LOV', example_entry='N', field_type='DP',
              inputs='gwWellDry', ingest_source_type='DP_TABLE', ingest_source_type_param=None, time_index=None,
              time_description=None, download_package='basic', data_category='N', sample_info=None,
              lov_code='Yes or No choice', primary_key='N', unit_name='NA', redaction_flag=None),
        Field(field_id=17852, table_id=1550, rank=21, data_product_number=None, field_name='trollPressureKpa',
              description='Water pressure measured by troll', data_type_code='real', meas_scale='ratio',
              ontology_mapping=None, pub_format='*.#(round)', example_entry='N', field_type='DP',
              inputs='trollPressureKpa', ingest_source_type='DP_TABLE', ingest_source_type_param=None,
              time_index=None, time_description=None, download_package='basic', data_category='N', sample_info=None,
              lov_code=None, primary_key='N', unit_name='kilopascal', redaction_flag=None),
        Field(field_id=17853, table_id=1550, rank=22, data_product_number=None, field_name='wellWaterDepth',
              description='Depth of water in well from top of well casing', data_type_code='real',
              meas_scale='ratio', ontology_mapping=None, pub_format='*.###(round)', example_entry='1.8',
              field_type='DP', inputs='wellWaterDepth', ingest_source_type='DP_TABLE', ingest_source_type_param=None,
              time_index=None, time_description=None, download_package='basic', data_category='N', sample_info=None,
              lov_code=None, primary_key='N', unit_name='meter', redaction_flag=None),
        Field(field_id=17854, table_id=1550, rank=23, data_product_number=None, field_name='depthCheckTime',
              description='Time the depth of water measurement was taken', data_type_code='dateTime',
              meas_scale='dateTime', ontology_mapping=None, pub_format="yyyy-MM-dd'T'HH:mm'Z'(floor)",
              example_entry='13:30', field_type='DP', inputs='depthCheckTime', ingest_source_type='DP_TABLE',
              ingest_source_type_param=None, time_index=None, time_description=None, download_package='basic',
              data_category='N', sample_info=None, lov_code=None, primary_key='N', unit_name='NA',
              redaction_flag=None),
        Field(field_id=17855, table_id=1550, rank=24, data_product_number=None, field_name='gwWellTrollCableLength',
              description='Length of troll cable in groundwater well', data_type_code='real', meas_scale='ratio',
              ontology_mapping=None, pub_format='*.###(round)', example_entry='1.2', field_type='DP',
              inputs='gwWellTrollCableLength', ingest_source_type='DP_TABLE', ingest_source_type_param=None,
              time_index=None, time_description=None, download_package='basic', data_category='N', sample_info=None,
              lov_code=None, primary_key='N', unit_name='meter', redaction_flag=None),
        Field(field_id=17856, table_id=1550, rank=25, data_product_number=None, field_name='batteryChecked',
              description='Indicator of whether the battery was checked', data_type_code='string',
              meas_scale='nominal', ontology_mapping=None, pub_format='LOV', example_entry='N', field_type='DP',
              inputs='batteryChecked', ingest_source_type='DP_TABLE', ingest_source_type_param=None, time_index=None,
              time_description=None, download_package='basic', data_category='N', sample_info=None,
              lov_code='Yes or No choice', primary_key='N', unit_name='NA', redaction_flag=None),
        Field(field_id=17857, table_id=1550, rank=26, data_product_number=None, field_name='gwWellBatteryVoltage',
              description='Voltage measured on the well battery', data_type_code='real', meas_scale='ratio',
              ontology_mapping=None, pub_format='*.#(round)', example_entry='12.3', field_type='DP',
              inputs='gwWellBatteryVoltage', ingest_source_type='DP_TABLE', ingest_source_type_param=None,
              time_index=None, time_description=None, download_package='basic', data_category='N', sample_info=None,
              lov_code=None, primary_key='N', unit_name='volt', redaction_flag=None),
        Field(field_id=17858, table_id=1550, rank=27, data_product_number=None, field_name='trollDesiccantExpired',
              description='Indicator of whether the troll desiccant was expired', data_type_code='string',
              meas_scale='nominal', ontology_mapping=None, pub_format='LOV', example_entry='N', field_type='DP',
              inputs='trollDesiccantExpired', ingest_source_type='DP_TABLE', ingest_source_type_param=None,
              time_index=None, time_description=None, download_package='basic', data_category='N', sample_info=None,
              lov_code='Yes or No choice', primary_key='N', unit_name='NA', redaction_flag=None),
        Field(field_id=17859, table_id=1550, rank=28, data_product_number=None,
              field_name='solarPanelAndInfrastructureInspected',
              description='Indicator of whether the solar panel and infrastructure were inspected',
              data_type_code='string', meas_scale='nominal', ontology_mapping=None, pub_format='LOV',
              example_entry='N', field_type='DP', inputs='solarPanelAndInfrastructureInspected',
              ingest_source_type='DP_TABLE', ingest_source_type_param=None, time_index=None, time_description=None,
              download_package='basic', data_category='N', sample_info=None, lov_code='Yes or No choice',
              primary_key='N', unit_name='NA', redaction_flag=None),
        Field(field_id=17860, table_id=1550, rank=29, data_product_number=None, field_name='openingLidImpractical',
              description='Indicator of whether the internal well infrastructure could be inspected',
              data_type_code='string', meas_scale='nominal', ontology_mapping=None, pub_format='LOV',
              example_entry='Ran out of time', field_type='DP', inputs='openingLidImpractical',
              ingest_source_type='DP_TABLE', ingest_source_type_param=None, time_index=None, time_description=None,
              download_package='basic', data_category='N', sample_info=None, lov_code='ais.gwInspectionImpractical',
              primary_key='N', unit_name='NA', redaction_flag=None),
        Field(field_id=17861, table_id=1550, rank=30, data_product_number=None, field_name='cableAlignedCorrectly',
              description='Indicator of whether the sensor cable moved since last inspection',
              data_type_code='string', meas_scale='nominal', ontology_mapping=None, pub_format='LOV',
              example_entry='N', field_type='DP', inputs='cableAlignedCorrectly', ingest_source_type='DP_TABLE',
              ingest_source_type_param=None, time_index=None, time_description=None, download_package='basic',
              data_category='N', sample_info=None, lov_code='Yes or No choice', primary_key='N', unit_name='NA',
              redaction_flag=None),
        Field(field_id=17862, table_id=1550, rank=31, data_product_number=None, field_name='cableAlignmentCorrected',
              description='Indicator of whether the elevation of the sensor was corrected by moving the cable up or down',
              data_type_code='string', meas_scale='nominal', ontology_mapping=None, pub_format='LOV',
              example_entry='N', field_type='DP', inputs='cableAlignmentCorrected', ingest_source_type='DP_TABLE',
              ingest_source_type_param=None, time_index=None, time_description=None, download_package='basic',
              data_category='N', sample_info=None, lov_code='Yes or No choice', primary_key='N', unit_name='NA',
              redaction_flag=None),
        Field(field_id=17863, table_id=1550, rank=32, data_product_number=None, field_name='gwWellHeaving',
              description='Indicator of whether the groundwater well infrastructure exhibited signs of heaving',
              data_type_code='string', meas_scale='nominal', ontology_mapping=None, pub_format='LOV',
              example_entry='N', field_type='DP', inputs='gwWellHeaving', ingest_source_type='DP_TABLE',
              ingest_source_type_param=None, time_index=None, time_description=None, download_package='basic',
              data_category='N', sample_info=None, lov_code='Yes or No choice', primary_key='N', unit_name='NA',
              redaction_flag=None),
        Field(field_id=17864, table_id=1550, rank=33, data_product_number=None,
              field_name='gwWellLocationTrackingRecord',
              description='Specifies if a location tracking record was created for groundwater well cable length',
              data_type_code='string', meas_scale='textDomain', ontology_mapping=None, pub_format='asIs',
              example_entry='c667c87c-f6d2-4419-b33b-f152218a5327', field_type='DP',
              inputs='gwWellLocationTrackingRecord', ingest_source_type='DP_TABLE', ingest_source_type_param=None,
              time_index=None, time_description=None, download_package='basic', data_category='N', sample_info=None,
              lov_code=None, primary_key='N', unit_name='NA', redaction_flag=None),
        Field(field_id=17865, table_id=1550, rank=34, data_product_number=None, field_name='trollConditionInspected',
              description='Indicator of whether troll condition was inspected', data_type_code='string',
              meas_scale='nominal', ontology_mapping=None, pub_format='LOV', example_entry='N', field_type='DP',
              inputs='trollConditionInspected', ingest_source_type='DP_TABLE', ingest_source_type_param=None,
              time_index=None, time_description=None, download_package='basic', data_category='N', sample_info=None,
              lov_code='Yes or No choice', primary_key='N', unit_name='NA', redaction_flag=None),
        Field(field_id=17866, table_id=1550, rank=35, data_product_number=None, field_name='biofoulingLevel',
              description='Relative description of the amount of biofouling on sensor(s)', data_type_code='string',
              meas_scale='nominal', ontology_mapping=None, pub_format='LOV', example_entry='Heavy', field_type='DP',
              inputs='biofoulingLevel', ingest_source_type='DP_TABLE', ingest_source_type_param=None,
              time_index=None, time_description=None, download_package='basic', data_category='N', sample_info=None,
              lov_code='ais.biofouling', primary_key='N', unit_name='NA', redaction_flag=None),
        Field(field_id=17867, table_id=1550, rank=36, data_product_number=None,
              field_name='trollGuardCleanedOrReplaced',
              description='Indicator of whether troll guard was cleaned or replaced', data_type_code='string',
              meas_scale='nominal', ontology_mapping=None, pub_format='LOV', example_entry='N', field_type='DP',
              inputs='trollGuardCleanedOrReplaced', ingest_source_type='DP_TABLE', ingest_source_type_param=None,
              time_index=None, time_description=None, download_package='basic', data_category='N', sample_info=None,
              lov_code='Yes or No choice', primary_key='N', unit_name='NA', redaction_flag=None),
        Field(field_id=17868, table_id=1550, rank=37, data_product_number=None, field_name='gwWellDryClarity',
              description='Indicator of whether the groundwater well contains water', data_type_code='string',
              meas_scale='nominal', ontology_mapping=None, pub_format='LOV', example_entry='N', field_type='DP',
              inputs='gwWellDryClarity', ingest_source_type='DP_TABLE', ingest_source_type_param=None,
              time_index=None, time_description=None, download_package='basic', data_category='N', sample_info=None,
              lov_code='Yes or No choice', primary_key='N', unit_name='NA', redaction_flag=None),
        Field(field_id=17869, table_id=1550, rank=38, data_product_number=None,
              field_name='waterClarityQuarterlyCheck',
              description='Indicator of whether the quarterly water clarity check was performed',
              data_type_code='string', meas_scale='nominal', ontology_mapping=None, pub_format='LOV',
              example_entry='N', field_type='DP', inputs='waterClarityQuarterlyCheck', ingest_source_type='DP_TABLE',
              ingest_source_type_param=None, time_index=None, time_description=None, download_package='basic',
              data_category='N', sample_info=None, lov_code='Yes or No choice', primary_key='N', unit_name='NA',
              redaction_flag=None),
        Field(field_id=17870, table_id=1550, rank=39, data_product_number=None, field_name='clarityCheckImpractical',
              description='Indicates if clarity check could not be performed', data_type_code='string',
              meas_scale='nominal', ontology_mapping=None, pub_format='LOV', example_entry='Location dry',
              field_type='DP', inputs='clarityCheckImpractical', ingest_source_type='DP_TABLE',
              ingest_source_type_param=None, time_index=None, time_description=None, download_package='basic',
              data_category='N', sample_info=None, lov_code='samplingImpractical', primary_key='N', unit_name='NA',
              redaction_flag=None),
        Field(field_id=17871, table_id=1550, rank=40, data_product_number=None, field_name='gwWellClarityLevel',
              description='Level of water clarity', data_type_code='string', meas_scale='nominal',
              ontology_mapping=None, pub_format='LOV', example_entry='Transparent', field_type='DP',
              inputs='gwWellClarityLevel', ingest_source_type='DP_TABLE', ingest_source_type_param=None,
              time_index=None, time_description=None, download_package='basic', data_category='N', sample_info=None,
              lov_code='ais.clarityLevel', primary_key='N', unit_name='NA', redaction_flag=None),
        Field(field_id=17872, table_id=1550, rank=41, data_product_number=None, field_name='clarityPhotoURL',
              description='The URL of the groundwater well clarity photo', data_type_code='string',
              meas_scale='textDomain', ontology_mapping=None, pub_format='asIs',
              example_entry='https://web.fulcrumapp.com/photos/view?photos=c667c87c-f6d2-4419-b33b-f152218a5327',
              field_type='DP', inputs='clarityPhotoURL', ingest_source_type='DP_TABLE',
              ingest_source_type_param=None, time_index=None, time_description=None, download_package='basic',
              data_category='N', sample_info=None, lov_code=None, primary_key='N', unit_name='NA',
              redaction_flag=None),
        Field(field_id=17873, table_id=1550, rank=42, data_product_number=None,
              field_name='ironBacteriaPreviouslyPresent',
              description='Indicator of whether iron-oxidizing bacteria are known to have been present in the groundwater well in the past',
              data_type_code='string', meas_scale='nominal', ontology_mapping=None, pub_format='LOV',
              example_entry='N', field_type='DP', inputs='ironBacteriaPreviouslyPresent',
              ingest_source_type='DP_TABLE', ingest_source_type_param=None, time_index=None, time_description=None,
              download_package='basic', data_category='N', sample_info=None, lov_code='Yes or No choice',
              primary_key='N', unit_name='NA', redaction_flag=None),
        Field(field_id=17874, table_id=1550, rank=43, data_product_number=None, field_name='ironBacteriaPresent',
              description='Indicator of whether iron-oxidizing bacteria were observed in the groundwater well',
              data_type_code='string', meas_scale='nominal', ontology_mapping=None, pub_format='LOV',
              example_entry='N', field_type='DP', inputs='ironBacteriaPresent', ingest_source_type='DP_TABLE',
              ingest_source_type_param=None, time_index=None, time_description=None, download_package='basic',
              data_category='N', sample_info=None, lov_code='Yes or No choice', primary_key='N', unit_name='NA',
              redaction_flag=None),
        Field(field_id=17875, table_id=1550, rank=44, data_product_number=None, field_name='evidenceOfRootsInWell',
              description='Indicator of whether there was evidence of roots in well', data_type_code='string',
              meas_scale='nominal', ontology_mapping=None, pub_format='LOV', example_entry='N', field_type='DP',
              inputs='evidenceOfRootsInWell', ingest_source_type='DP_TABLE', ingest_source_type_param=None,
              time_index=None, time_description=None, download_package='basic', data_category='N', sample_info=None,
              lov_code='Yes or No choice', primary_key='N', unit_name='NA', redaction_flag=None),
        Field(field_id=17876, table_id=1550, rank=45, data_product_number=None,
              field_name='gwWellDepthwaterAnnualCheck',
              description='Indicator of whether the annual groundwater well depth check was performed',
              data_type_code='string', meas_scale='nominal', ontology_mapping=None, pub_format='LOV',
              example_entry='N', field_type='DP', inputs='gwWellDepthwaterAnnualCheck',
              ingest_source_type='DP_TABLE', ingest_source_type_param=None, time_index=None, time_description=None,
              download_package='basic', data_category='N', sample_info=None, lov_code='Yes or No choice',
              primary_key='N', unit_name='NA', redaction_flag=None),
        Field(field_id=17877, table_id=1550, rank=46, data_product_number=None, field_name='previousTotalWellDepth',
              description='Total depth of well from previous measurement', data_type_code='real', meas_scale='ratio',
              ontology_mapping=None, pub_format='*.###(round)', example_entry='3.4', field_type='DP',
              inputs='previousTotalWellDepth', ingest_source_type='DP_TABLE', ingest_source_type_param=None,
              time_index=None, time_description=None, download_package='basic', data_category='N', sample_info=None,
              lov_code=None, primary_key='N', unit_name='meter', redaction_flag=None),
        Field(field_id=17878, table_id=1550, rank=47, data_product_number=None,
              field_name='newMeasurementWIthin10cm',
              description='Indicator of whether the new measurement is within 10cm of last measurement',
              data_type_code='string', meas_scale='nominal', ontology_mapping=None, pub_format='LOV',
              example_entry='N', field_type='DP', inputs='newMeasurementWIthin10cm', ingest_source_type='DP_TABLE',
              ingest_source_type_param=None, time_index=None, time_description=None, download_package='basic',
              data_category='N', sample_info=None, lov_code='Yes or No choice', primary_key='N', unit_name='NA',
              redaction_flag=None),
        Field(field_id=17879, table_id=1550, rank=48, data_product_number=None, field_name='totalWellDepth',
              description='Total well depth; used to calculate water column height', data_type_code='real',
              meas_scale='ratio', ontology_mapping=None, pub_format='*.###(round)', example_entry='3.5',
              field_type='DP', inputs='totalWellDepth', ingest_source_type='DP_TABLE', ingest_source_type_param=None,
              time_index=None, time_description=None, download_package='basic', data_category='N', sample_info=None,
              lov_code=None, primary_key='N', unit_name='meter', redaction_flag=None),
        Field(field_id=17880, table_id=1550, rank=49, data_product_number=None,
              field_name='gwWellsOpportunisticMaintenance',
              description='Unscheduled or corrective maintenance tasks performed at groundwater wells',
              data_type_code='string', meas_scale='textDomain', ontology_mapping=None, pub_format='asIs',
              example_entry='Sensor Repair', field_type='DP', inputs='gwWellsOpportunisticMaintenance',
              ingest_source_type='DP_TABLE', ingest_source_type_param=None, time_index=None, time_description=None,
              download_package='basic', data_category='N', sample_info=None, lov_code=None, primary_key='N',
              unit_name='NA', redaction_flag=None),
        Field(field_id=17881, table_id=1550, rank=50, data_product_number=None,
              field_name='gwWellRedevelopedDuringBout',
              description='Indicator of whether groundwater well redeveloped during the sampling bout',
              data_type_code='string', meas_scale='nominal', ontology_mapping=None, pub_format='LOV',
              example_entry='N', field_type='DP', inputs='gwWellRedevelopedDuringBout',
              ingest_source_type='DP_TABLE', ingest_source_type_param=None, time_index=None, time_description=None,
              download_package='basic', data_category='N', sample_info=None, lov_code='Yes or No choice',
              primary_key='N', unit_name='NA', redaction_flag=None),
        Field(field_id=17882, table_id=1550, rank=51, data_product_number=None, field_name='gwWellRemarks',
              description='Remarks about the groundwater well', data_type_code='string', meas_scale='textDomain',
              ontology_mapping=None, pub_format='asIs', example_entry='external battery replaced', field_type='DP',
              inputs='gwWellRemarks', ingest_source_type='DP_TABLE', ingest_source_type_param=None, time_index=None,
              time_description=None, download_package='basic', data_category='N', sample_info=None, lov_code=None,
              primary_key='N', unit_name='NA', redaction_flag=None),
        Field(field_id=17883, table_id=1550, rank=52, data_product_number=None, field_name='fulcrumVersion',
              description='Version of the Fulcrum application used during data entry', data_type_code='string',
              meas_scale='textDomain', ontology_mapping=None, pub_format='asIs', example_entry='1.0.0',
              field_type='DP', inputs='fulcrumVersion', ingest_source_type='DP_TABLE', ingest_source_type_param=None,
              time_index=None, time_description=None, download_package='basic', data_category='N', sample_info=None,
              lov_code=None, primary_key='N', unit_name='NA', redaction_flag=None),
        Field(field_id=17884, table_id=1550, rank=53, data_product_number=None, field_name='platformInfo',
              description='Operating System and browser information (where applicable) of computer used during data entry',
              data_type_code='string', meas_scale='textDomain', ontology_mapping=None, pub_format='asIs',
              example_entry='Windows 10', field_type='DP', inputs='platformInfo', ingest_source_type='DP_TABLE',
              ingest_source_type_param=None, time_index=None, time_description=None, download_package='basic',
              data_category='N', sample_info=None, lov_code=None, primary_key='N', unit_name='NA',
              redaction_flag=None),
        Field(field_id=17885, table_id=1550, rank=54, data_product_number=None, field_name='dataQF',
              description='Data quality flag', data_type_code='string', meas_scale='textDomain',
              ontology_mapping=None, pub_format='asIs', example_entry='ok', field_type='DP', inputs='dataQF',
              ingest_source_type='DP_TABLE', ingest_source_type_param=None, time_index=None, time_description=None,
              download_package='basic', data_category='N', sample_info=None, lov_code=None, primary_key='N',
              unit_name='NA', redaction_flag=None)
    ]
