# Default workflow for applying calibration to raw sensor data.
# This workflow template accepts a manifest of datums (paths) to retrieve and process.
# Each datum can be specified to whatever path makes sense. For example, can specify to 
# the /source_type/year/month/day, or to the /source_type/year/month/day/source-id
# The data is loaded to a local volume.
# The calibration group and convert module processes whatever is in the volume.
# The final output is copied to a specified repo in the specified output bucket
# The next workflow in the series is spawned, as read from a configmap

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: cal-conv
spec:
  # You can set sensible defaults here, can override in the workflow
  entrypoint: run
  # This block for granting setting the group permissions on the emptyDir volumes
  securityContext:
    fsGroup: 1001
    fsGroupChangePolicy: OnRootMismatch
  arguments:
    parameters:
      - name: datum-manifest # Data loader
        value: |
          {"paths": ["cmp22/2025/10/01/11185","cmp22/2026/05/01/11185","cmp22/2026/05/02/11183"]}
      - name: env_config # ConfigMap holding environment vars
        value: cmp22-cal-group-convert-env

  templates:
    - name: run
      volumes:
        - name: in-vol
          emptyDir: { }
        - name: out-vol
          emptyDir: { }
        - name: tmp-vol
          emptyDir: { }
          
      inputs:
        parameters:
        - name: datum-manifest
        - name: schema-repo-eng-url # Must be defined here bc can't access configmap in same parameter block above where it is defined 
          valueFrom:
            configMapKeyRef:
              name: "{{workflow.parameters.env_config}}"
              key: schema-repo-eng-url
        - name: schema-repo-eng-revision
          valueFrom:
            configMapKeyRef:
              name: "{{workflow.parameters.env_config}}"
              key: schema-repo-eng-revision
        - name: schema-repo-sci-url # Must be defined here bc can't access configmap in same parameter block above where it is defined 
          valueFrom:
            configMapKeyRef:
              name: "{{workflow.parameters.env_config}}"
              key: schema-repo-sci-url
        - name: schema-repo-sci-revision
          valueFrom:
            configMapKeyRef:
              name: "{{workflow.parameters.env_config}}"
              key: schema-repo-sci-revision
        artifacts: 
        - name: schemas-eng
          path: /inputs/schemas-eng
          git:
            repo: "{{inputs.parameters.schema-repo-eng-url}}"
            revision: "{{inputs.parameters.schema-repo-eng-revision}}"
            depth: 1
            sshPrivateKeySecret:
              name: neon-avro-schemas-secret-readonly
              key: sshPrivateKey
        - name: schemas-sci
          path: /inputs/schemas-sci
          git:
            repo: "{{inputs.parameters.schema-repo-sci-url}}"
            revision: "{{inputs.parameters.schema-repo-sci-revision}}"
            depth: 1

      containerSet:
        # Note: Must mount volume with the input artifact(s) in order to have it accessible to all containers 
        #   (otherwise it is only accessible to the "main" container). Same goes for outputs.
        volumeMounts:
          - name: in-vol
            mountPath: /inputs
          - name: out-vol
            mountPath: /pfs
          - name: tmp-vol
            mountPath: /tmp # /tmp is required to run R code if it ever creates a temp directory
            
        containers:
          - name: load-data
            image: us-central1-docker.pkg.dev/neon-shared-service/neonscience/neon-is-gcs-data:sha-fb7a80e
            # Need to run as user 1001 because the gcs input is loaded as this user and group, as controlled by the helm chart.
            # Note that the image might set the user and group as something else, but this doesn't matter because we don't need write priveleges in the container
            securityContext:
              runAsUser: 1001 
              runAsGroup: 1001
            resources:
              requests:
                memory: "300Mi"
                cpu: "100m"
              limits:
                memory: "500Mi"
                cpu: "1"
            command:
            - bash
            - -c
            - |
              # Use bash-scrict mode. See http://redsymbol.net/articles/unofficial-bash-strict-mode/
              set -euo pipefail
              IFS=$'\n\t'

              # Get L0 data from GCS
              python3 -m l0_gcs_loader_by_manifest

              # Get assigned calibrations 
              CAL_REPO="cmp22_calibration_assignment"
              CAL_DEST="/inputs/CALIBRATION_PATH"
              
              #set -x  # Uncomment for troubleshooting
              
              # Normalize repo prefixes (remove leading/trailing slashes)
              CAL_REPO="${CAL_REPO#/}"
              CAL_REPO="${CAL_REPO%/}"
              CAL_ROOT=":gcs://${CAL_BUCKET_NAME}/${CAL_REPO}"
              
              mkdir -p "$CAL_DEST"
              
              echo "Datum Manifest:        $MANIFEST"
              # echo "Data Root:             $DATA_ROOT"
              # echo "Data Dest:             $DATA_DEST"
              echo "Cal Root:              $CAL_ROOT"
              echo "Cal Dest:              $CAL_DEST"
              echo


              for datum_path in $(printf '%s' "$MANIFEST" | jq -r '.paths[]'); do

                echo "DATUM: $datum_path"

                # Get calibrations
                echo "Getting calibration datum: $datum_path"
                
                src="${CAL_ROOT}/${datum_path}"
                dst="${CAL_DEST}/${datum_path}"
                mkdir -p "$dst"

                rclone \
                  --no-check-dest \
                  --copy-links \
                  --gcs-bucket-policy-only \
                  --gcs-no-check-bucket \
                  copy \
                  --progress \
                  "${src}" "${dst}" 
              done
              
              echo "Done getting data and calibrations."
              
              #set +x # Uncomment for troubleshooting
                        
            env:
              # Environment variables for data download
              - name: MANIFEST
                value: "{{inputs.parameters.datum-manifest}}"
              - name: BUCKET_NAME
                valueFrom:
                  configMapKeyRef:
                    name: "{{workflow.parameters.env_config}}"
                    key: l0-bucket-name
              - name: BUCKET_VERSION_PATH
                valueFrom:
                  configMapKeyRef:
                    name: "{{workflow.parameters.env_config}}"
                    key: l0-bucket-version-path
              - name: CAL_BUCKET_NAME
                valueFrom:
                  configMapKeyRef:
                    name: "{{workflow.parameters.env_config}}"
                    key: cal-bucket-name
              - name: SOURCE_TYPE_INDEX
                valueFrom:
                  configMapKeyRef:
                    name: "{{workflow.parameters.env_config}}"
                    key: source-type-index
              - name: YEAR_INDEX
                valueFrom:
                  configMapKeyRef:
                    name: "{{workflow.parameters.env_config}}"
                    key: year-index
              - name: MONTH_INDEX
                valueFrom:
                  configMapKeyRef:
                    name: "{{workflow.parameters.env_config}}"
                    key: month-index
              - name: DAY_INDEX
                valueFrom:
                  configMapKeyRef:
                    name: "{{workflow.parameters.env_config}}"
                    key: day-index
              - name: SOURCE_ID_INDEX
                valueFrom:
                  configMapKeyRef:
                    name: "{{workflow.parameters.env_config}}"
                    key: source-id-index
              - name: OUT_PATH
                valueFrom:
                  configMapKeyRef:
                    name: "{{workflow.parameters.env_config}}"
                    key: out-path-l0
              - name: LOG_LEVEL
                valueFrom:
                  configMapKeyRef:
                    name: "{{workflow.parameters.env_config}}"
                    key: log-level


          - name: calibration-group-and-convert
            dependencies:
              - load-data
            image: us-central1-docker.pkg.dev/neon-shared-service/neonscience/neon-is-cal-grp-conv:v3.1.0
            # Need to run as user 1001 because the gcs input is loaded as this user and group, as controlled by the helm chart.
            # Note that the image sets the user and group as 9999, but this doesn't seem to matter because we don't need write priveleges in the container
            securityContext:
              runAsUser: 1001 
              runAsGroup: 1001
              
            # NOTE: The individual resources requested for each container don't really matter. 
            #   It's the sum total of them that is actually available to each container, so long as they run in sequence.
            #   Any containers that run in parallel need to have the sum of their resource needs available
            resources:
              requests:
                memory: "700Mi"
                cpu: "1"
              limits:
                memory: "1Gi"
                cpu: "1.25"
            command:
            - bash
            - -c
            - |
              # Use bash-scrict mode. See http://redsymbol.net/articles/unofficial-bash-strict-mode/
              set -euo pipefail
              IFS=$'\n\t'

              # Join files from the archive and from Kafka
              export OUT_PATH=$OUT_PATH_JOINER
              python3 -m filter_joiner.filter_joiner_main

              # Combine data from Kafka and the archive
              # In this case we are just removing fields outside the schema
              eval "Rscript ./flow.kfka.comb.R $KFKA_COMB_R_ARGS"
    
              # Run calibration conversion module
              eval "Rscript ./flow.cal.conv.R $CAL_CONV_R_ARGS"
              
            env:
              # Environment variables for filter-joiner
              - name: CONFIG
                valueFrom:
                  configMapKeyRef:
                    name: "{{workflow.parameters.env_config}}"
                    key: filter-joiner-config
              - name: OUT_PATH_JOINER
                valueFrom:
                  configMapKeyRef:
                    name: "{{workflow.parameters.env_config}}"
                    key: out-path-joiner
              - name: OUT_PATH_KAFKA_COMB
                valueFrom:
                  configMapKeyRef:
                    name: "{{workflow.parameters.env_config}}"
                    key: out-path-kafka-comb
              - name: OUT_PATH_CAL_CONV
                valueFrom:
                  configMapKeyRef:
                    name: "{{workflow.parameters.env_config}}"
                    key: out-path-cal-conv
              - name: ERR_PATH
                valueFrom:
                  configMapKeyRef:
                    name: "{{workflow.parameters.env_config}}"
                    key: err-path
              - name: LOG_LEVEL
                valueFrom:
                  configMapKeyRef:
                    name: "{{workflow.parameters.env_config}}"
                    key: log-level
              - name: RELATIVE_PATH_INDEX
                valueFrom:
                  configMapKeyRef:
                    name: "{{workflow.parameters.env_config}}"
                    key: relative-path-index
              - name: LINK_TYPE
                valueFrom:
                  configMapKeyRef:
                    name: "{{workflow.parameters.env_config}}"
                    key: link-type
              - name: FILE_SCHEMA_L0
                valueFrom:
                  configMapKeyRef:
                    name: "{{workflow.parameters.env_config}}"
                    key: file-schema-l0
              - name: FILE_SCHEMA_CALIBRATED_DATA
                valueFrom:
                  configMapKeyRef:
                    name: "{{workflow.parameters.env_config}}"
                    key: file-schema-calibrated-data
              - name: FILE_SCHEMA_CALIBRATION_FLAGS
                valueFrom:
                  configMapKeyRef:
                    name: "{{workflow.parameters.env_config}}"
                    key: file-schema-calibration-flags
              - name: FILE_UNCERTAINTY_FDAS
                valueFrom:
                  configMapKeyRef:
                    name: "{{workflow.parameters.env_config}}"
                    key: file-uncertainty-fdas
              - name: PARALLELISM_INTERNAL
                valueFrom:
                  configMapKeyRef:
                    name: "{{workflow.parameters.env_config}}"
                    key: parallelism-internal
              - name: KFKA_COMB_R_ARGS
                valueFrom:
                  configMapKeyRef:
                    name: "{{workflow.parameters.env_config}}"
                    key: kfka-comb-r-args
              - name: CAL_CONV_R_ARGS
                valueFrom:
                  configMapKeyRef:
                    name: "{{workflow.parameters.env_config}}"
                    key: cal-conv-r-args
          - name: main
            dependencies:
              - calibration-group-and-convert
            image: us-central1-docker.pkg.dev/neon-shared-service/neonscience/neon-is-gcs-data:v1.0.0
            # Need to run as user 1001 because the gcs input is loaded as this user and group, as controlled by the helm chart.
            # Note that the image sets the user and group as 9999, but this doesn't seem to matter because we don't need write priveleges in the container
            securityContext:
              runAsUser: 1001 
              runAsGroup: 1001
            resources:
              requests:
                memory: "300Mi"
                cpu: "100m"
              limits:
                memory: "500Mi"
                cpu: "1"
            command:
            - bash
            - -c
            - |
              # Use bash-scrict mode. See http://redsymbol.net/articles/unofficial-bash-strict-mode/
              set -euo pipefail
              IFS=$'\n\t'
              
              ls -l $OUT_PATH

              # Export data to bucket
              if [[ -d "$OUT_PATH" ]]; then
                linkdir=$(mktemp -d)
                shopt -s globstar
                out_parquet_glob="${OUT_PATH}/**/*.*" # Get all files, assuming there is an extension
                # Example: /pfs/out/cmp22/2023/01/01/12345/data/file.parquet
                echo "Linking output files to ${linkdir}"
                # set -x # Uncomment for troubleshooting
                for f in $out_parquet_glob; do
                  # Parse the path
                  [[ "$f" =~ ^$OUT_PATH/(.*)$ ]]
                  rel_path="${BASH_REMATCH[1]}"
                  fname="${rel_path##*/}"
                  rel_dir="${rel_path%/*}"
                  outdir="${linkdir}/${OUTPUT_BUCKET_PREFIX}/${rel_dir}"
                  mkdir -p "${outdir}"
                  ln -s "${f}" "${outdir}"
                done
          
                echo "Syncing files to bucket"
                rclone \
                  --copy-links \
                  --gcs-bucket-policy-only \
                  copy \
                  "${linkdir}/${OUTPUT_BUCKET_PREFIX}" \
                  ":gcs://${OUTPUT_BUCKET_NAME}/${OUTPUT_BUCKET_PREFIX}"
                  
                echo "Removing temporary files"
                rm -rf $linkdir
                
                # set +x # Uncomment for troubleshooting
              fi
                        
            env:
              # Environment variables for data upload
              - name: OUT_PATH
                valueFrom:
                  configMapKeyRef:
                    name: "{{workflow.parameters.env_config}}"
                    key: out-path-cal-conv
              - name: OUTPUT_BUCKET_NAME
                valueFrom:
                  configMapKeyRef:
                    name: "{{workflow.parameters.env_config}}"
                    key: output-bucket-name
              - name: OUTPUT_BUCKET_PREFIX
                valueFrom:
                  configMapKeyRef:
                    name: "{{workflow.parameters.env_config}}"
                    key: output-bucket-prefix
