apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp22-next-workflows
  namespace: argo-workflows-dev
  labels:
    # Note that this label is required for the informer to detect this ConfigMap.
    workflows.argoproj.io/configmap-type: Parameter
data:
  next-wfs-cal-conv: |
    workflows:
      - cmp22-loc-strc
      - test-input-artifact
