apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-workflows-dev

resources:
  - ../../base
  - configmap-parameters.yaml

patches:
  - patch: |-
      apiVersion: argoproj.io/v1alpha1
      kind: WorkflowTemplate
      metadata:
        name: calibration-group-and-convert
      spec:
        arguments:
          parameters:
            - name: configmap-parameters
              value: aepg600m-heated-calibration-group-convert-config

commonLabels:
  sensor: aepg600m_heated
  workflow: calibration-group-and-convert