#!/bin/bash

# Generate the tempAirSingle pipeline. The prt pipeline must be created before this pipeline.

# Prerequisite pipelines: data_source_windobserverii, data_source_prt, calibration, data_source_dualfan,
# avro_schemas, threshold

pachctl start transaction

pachctl create pipeline -f windobserverii_data_location_group/windobserverii_data_location_group.json
pachctl create pipeline -f heater_data_location_group/heater_data_location_group.json
pachctl create pipeline -f dualfan_data_location_group/dualfan_data_location_group.json
pachctl create pipeline -f windobserverii_location_filter/windobserverii_location_filter.json
pachctl create pipeline -f dualfan_location_filter/dualfan_location_filter.json
pachctl create pipeline -f windobserverii_structure_repo_by_location/windobserverii_structure_repo_by_location.json
pachctl create pipeline -f dualfan_structure_repo_by_location/dualfan_structure_repo_by_location.json
pachctl create pipeline -f windobserverii_merge_data_by_location/windobserverii_merge_data_by_location.json
pachctl create pipeline -f dualfan_merge_data_by_location/dualfan_merge_data_by_location.json
pachctl create pipeline -f tempAirSingle_windobserverii_group_path/tempAirSingle_windobserverii_group_path.json
pachctl create pipeline -f tempAirSingle_heater_group_path/tempAirSingle_heater_group_path.json
pachctl create pipeline -f tempAirSingle_dualfan_group_path/tempAirSingle_dualfan_group_path.json
pachctl create pipeline -f tempAirSingle_related_location_group/tempAirSingle_related_location_group.json
pachctl create pipeline -f tempAirSingle_dualfan/tempAirSingle_dualfan.json
pachctl create pipeline -f tempAirSingle_prt/tempAirSingle_prt.json
pachctl create pipeline -f tempAirSingle_threshold_filter/tempAirSingle_threshold_filter.json
pachctl create pipeline -f tempAirSingle_locations/tempAirSingle_locations.json
pachctl create pipeline -f tempAirSingle_calibrated_data/tempAirSingle_calibrated_data.json
pachctl create pipeline -f tempAirSingle_calibrated_flags/tempAirSingle_calibrated_flags.json
pachctl create pipeline -f tempAirSingle_uncertainty_fdas/tempAirSingle_uncertainty_fdas.json
pachctl create pipeline -f tempAirSingle_threshold_select/tempAirSingle_threshold_select.json
pachctl create pipeline -f tempAirSingle_regularized_data/tempAirSingle_regularized_data.json
pachctl create pipeline -f tempAirSingle_threshold_regularized_group/tempAirSingle_threshold_regularized_group.json
pachctl create pipeline -f tempAirSingle_windobserverii/tempAirSingle_windobserverii.json
pachctl create pipeline -f tempAirSingle_heater/tempAirSingle_heater.json
pachctl create pipeline -f tempAirSingle_timeseries_padder/tempAirSingle_timeseries_padder.json
pachctl create pipeline -f tempAirSingle_qaqc_specific_group/tempAirSingle_qaqc_specific_group.json
pachctl create pipeline -f tempAirSingle_uncertainty_coefficients/tempAirSingle_uncertainty_coefficients.json
pachctl create pipeline -f tempAirSingle_padded_timeseries_analyzer/tempAirSingle_padded_timeseries_analyzer.json
pachctl create pipeline -f tempAirSingle_qaqc_specific/tempAirSingle_qaqc_specific.json
pachctl create pipeline -f tempAirSingle_regularized_uncertainty_fdas/tempAirSingle_regularized_uncertainty_fdas.json
pachctl create pipeline -f tempAirSingle_qaqc_plausibility/tempAirSingle_qaqc_plausibility.json
pachctl create pipeline -f tempAirSingle_qaqc_specific_flags/tempAirSingle_qaqc_specific_flags.json
pachctl create pipeline -f tempAirSingle_qaqc_specific_data/tempAirSingle_qaqc_specific_data.json
pachctl create pipeline -f tempAirSingle_qaqc_plausibility_flags/tempAirSingle_qaqc_plausibility_flags.json
pachctl create pipeline -f tempAirSingle_regularized_flags/tempAirSingle_regularized_flags.json
pachctl create pipeline -f tempAirSingle_qaqc_plausibility_data/tempAirSingle_qaqc_plausibility_data.json
pachctl create pipeline -f tempAirSingle_qaqc_flags_group/tempAirSingle_qaqc_flags_group.json
pachctl create pipeline -f tempAirSingle_qaqc_data_group/tempAirSingle_qaqc_data_group.json
pachctl create pipeline -f tempAirSingle_quality_metrics/tempAirSingle_quality_metrics.json
pachctl create pipeline -f tempAirSingle_merge_qaqc_data/tempAirSingle_merge_qaqc_data.json
pachctl create pipeline -f tempAirSingle_statistics_uncertainty_group/tempAirSingle_statistics_uncertainty_group.json
pachctl create pipeline -f tempAirSingle_statistics/tempAirSingle_statistics.json
pachctl create pipeline -f tempAirSingle_level1_group/tempAirSingle_level1_group.json

pachctl finish transaction
