pachctl begin transaction

pachctl create pipeline -f prt_data_calibration_group/prt_data_calibration_group.json
pachctl create pipeline -f prt_calibration_filter/prt_calibration_filter.json
pachctl create pipeline -f prt_calibration_conversion/prt_calibration_conversion.json
pachctl create pipeline -f prt_calibration_location_group/prt_calibration_location_group.json
pachctl create pipeline -f prt_location_filter/prt_location_filter.json
pachctl create pipeline -f prt_structure_repo_by_location/prt_structure_repo_by_location.json
pachctl create pipeline -f prt_merge_data_by_location/prt_merge_data_by_location.json
pachctl create pipeline -f prt_fill_date_gaps_by_location/prt_fill_date_gaps_by_location.json

pachctl finish transaction