# Dockerfile for NEON IS Data Processing - Test script

# Start with the base image. 
FROM quay.io/battelleecology/neon-is-base-r:v0.0.51

# maintainer handle
MAINTAINER "Cove Sturtevant" csturtevant@battelleecology.org

# Copy in test workflow
COPY ./flow.test.pach.R /flow.test.pach.R
