name: "Run R unit tests"
description: "Run R unit tests on NEONprocIS.base"

runs:
   using: "composite"
   steps: 
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.1.3

      - name: Install R packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
              fs
              devtools
              rapportools
              arrow@14.0.0
              dplyr@1.1.3
          extra-packages: |
              any::covr
              any::xml2
          needs: coverage
          cache: always

      - name: Add libR.so to LD_LIBRARY_PATH
        shell: bash
        run: |
          LIBR_DIR=$(dirname $(find /opt -name "libR.so" | head -n 1))
          echo "LD_LIBRARY_PATH=$LIBR_DIR:$LD_LIBRARY_PATH" >> $GITHUB_ENV

      - name: Install Avro
        run: sudo apt install libavro23

      - name: Run unit test coverage using covr package
        shell: Rscript {0}
        run: |
          # read the library versions from renv.lock
          # renv::use(lockfile = "${{ env.MODULE_PATH }}/renv.lock")
          devtools::install("${{ env.MODULE_PATH }}")
          library(NEONprocIS.base)
          library(dplyr)
          library(arrow)
          library(jsonlite)
          library(base)
          library(utils)
          library(rlang)
          library(stringr)
          devtools::test(pkg="${{ env.MODULE_PATH }}")
          cov <- covr::package_coverage(path="${{ env.MODULE_PATH }}")
          covr::report(cov, file="${{ env.MODULE_NAME }}-coverage.html")
  
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ${{ env.MODULE_NAME }}-coverage.html
