name: "Run R unit tests"
description: "Run R unit tests on NEONprocIS.base"

inputs:
  image-tag:
    required: true

runs:
   using: "composite"
   steps: 
      - name: Build Docker Image
        id: build
        uses: docker/build-push-action@v5
        with:
            context: ./
            file: ${{ env.MODULE_PATH }}/Dockerfile
            push: false
            tags: ${{ env.IMAGE_NAME }}:${{ inputs.image-tag }}
  
      - name: Run unit tests inside Docker container
        shell: bash
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            -e MODULE_PATH=${{ env.MODULE_PATH }} \
            -e MODULE_NAME=${{ env.MODULE_NAME }} \
            ${{ env.IMAGE_NAME }}:${{ inputs.image-tag }} \
            Rscript ${{ env.MODULE_PATH }}/run-tests.R

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ${{ env.MODULE_NAME }}-cobertura.xml
