name: "Run IS base package unit tests"

on:
  push:
    branches:
      - master
    paths:
      - 'pack/NEONprocIS.base/**'
      
  workflow_dispatch: {} # Allows trigger of workflow from web interface

env:
  # IS package name
  MODULE_PATH: ./pack/NEONprocIS.base
  MODULE_NAME: NEONprocIS.base

jobs:
  run-unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4.1.4"
        with:
          fetch-depth: '0'

      - name: Run IS base package unit tests
        uses: ./.github/actions/run-r-unit-tests
