---
# General configuration for assignment workflows.
apiVersion: v1
kind: ConfigMap
metadata:
  name: assignment-base-config
  namespace: argo-workflows-dev
  labels:
    # This label is required for the informer to detect this ConfigMap
    workflows.argoproj.io/configmap-type: Parameter
data:
  # Images
  io_image: "us-central1-docker.pkg.dev/neon-shared-service/bei/neon-argo-workflows-data-change-manifest:sha-05b282b"
  assign_location_groups_image: "us-central1-docker.pkg.dev/neon-shared-service/neonscience/neon-is-loc-grp-asgn:v1.4.0"