---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo-workflows-dev
resources:
  - assignment_config.yaml
  - metadata_git_repo_config.yaml
  - location_group_assignment_template.yaml