---
# Workflow for assigning location/asset/group metadata to data dates.
# The data is loaded to a shared volume.
# The assignment script processes whatever is in the volume.
# The final output manifests are written into the output bucket.
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: location-group-assignment-template
spec:
  entrypoint: main
  templates:
    - name: main
      inputs:
        parameters:
          - name: source_type
          - name: r_args
          - name: source_id_path_index
          # ConfigMap constants.
          - name: log_level
            valueFrom:
              configMapKeyRef:
                name: "{{workflow.parameters.configuration}}"
                key: log_level
          # Git
          - name: git_secret_name
            valueFrom:
              configMapKeyRef:
                name: "{{workflow.parameters.configuration}}"
                key: git_secret_name
          - name: git_secret_file_name
            valueFrom:
              configMapKeyRef:
                name: "{{workflow.parameters.configuration}}"
                key: git_secret_file_name
          - name: git_repo_url
            valueFrom:
              configMapKeyRef:
                name: "{{workflow.parameters.configuration}}"
                key: git_repo_url
          - name: git_branch
            valueFrom:
              configMapKeyRef:
                name: "{{workflow.parameters.configuration}}"
                key: git_branch
          - name: git_repo_dir
            valueFrom:
              configMapKeyRef:
                name: "{{workflow.parameters.configuration}}"
                key: git_repo_dir
          # Output bucket for writing results.
          - name: output_bucket
            valueFrom:
              configMapKeyRef:
                name: "{{workflow.parameters.configuration}}"
                key: output_bucket
          - name: output_bucket_prefix
            valueFrom:
              configMapKeyRef:
                name: "{{workflow.parameters.configuration}}"
                key: output_bucket_prefix
          # Assignment script configuration.
          - name: parallelization_internal
            valueFrom:
              configMapKeyRef:
                name: "{{workflow.parameters.configuration}}"
                key: parallelization_internal
          - name: relative_path_index
            valueFrom:
              configMapKeyRef:
                name: "{{workflow.parameters.configuration}}"
                key: relative_path_index
          # Container images
          - name: io_image
            valueFrom:
              configMapKeyRef:
                name: base-assignment-config
                key: io_image
          - name: assignment_image
            valueFrom:
              configMapKeyRef:
                name: assignment-config
                key: location_group_assignment_image
      volumes:
        - name: workspace
          emptyDir: { }
        - name: tmp
          emptyDir: { }
        - name: git-secret
          secret:
            secretName: "{{inputs.parameters.git_secret_name}}"
      containerSet:
        # Mount volumes here to make them accessible to all containers.
        volumeMounts:
          - name: workspace
            mountPath: /workspace
        containers:
        # Load all changed metadata files from Git in the latest commit.
        - name: load
          image: "{{inputs.parameters.io_image}}"
          volumeMounts:
            - name: git-secret
              mountPath: /workspace/ssh_key
          resources:
            requests:
              memory: 1.5Gi
              cpu: 250m
            limits:
              memory: 2.5Gi
              cpu: 500m
          env:
            - name: DOWNLOAD_PATH
              value: /workspace/download_files
            - name: GIT_BRANCH
              value: "{{inputs.parameters.git_branch}}"
            - name: GIT_REPO_DIR
              value: "{{inputs.parameters.git_repo_dir}}"
            - name: GIT_REPO_URL
              value: "{{inputs.parameters.git_repo_url}}"
            - name: KEY_PATH
              value: "/workspace/ssh_key/{{inputs.parameters.git_secret_file_name}}"
            - name: LOGURU_LEVEL
              value: "{{inputs.parameters.log_level}}"
          command: [sh, -c]
          args: ["python3 /app/clone_changed_files.py"]
        # Assign the data to dates.
        - name: assign
          dependencies:
            - load
          image: "{{inputs.parameters.assignment_image}}"
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          resources:
            requests:
              memory: 3Gi
              cpu: 250m
            limits:
              memory: 4Gi
              cpu: 500m
          env:
            - name: DIR_IN
              value: /workspace/download_files
            - name: DIR_OUT
              value: /workspace/processed_files
            - name: ERR_PATH
              value: /workspace/error_files
            - name: LOG_LEVEL
              value: "{{inputs.parameters.log_level}}"
            - name: DATE_BEGIN
              value: "{{workflow.parameters.date_begin}}"
            - name: RELATIVE_PATH_INDEX
              value: "{{inputs.parameters.relative_path_index}}"
            - name: R_ARGS
              value: "{{inputs.parameters.r_args}}"
            - name: PARALLELIZATION_INTERNAL
              value: "{{inputs.parameters.parallelization_internal}}"
          command: [bash, -c]
          args:
            - |
              set -euo pipefail
              IFS=$'\n\t'
              export DATE_END=$(date -d "{{workflow.creationTimestamp}} +1 day" +%F)
              eval "Rscript ./flow.loc.grp.asgn.R $R_ARGS"
        # Generate the change manifest and write it to a bucket.
        - name: main
          dependencies:
            - assign
          image: "{{inputs.parameters.io_image}}"
          resources:
            requests:
              memory: 300Mi
              cpu: 250m
            limits:
              memory: 500Mi
              cpu: 500m
          env:
            - name: CHANGE_MANIFEST_FILE_NAME
              value: change_manifest.json
            - name: LOGURU_LEVEL
              value: "{{inputs.parameters.log_level}}"
            - name: MANIFEST_BUCKET
              value: "{{inputs.parameters.output_bucket}}"
            - name: MANIFEST_BUCKET_PREFIX
              value: "{{inputs.parameters.output_bucket_prefix}}"
            - name: MANIFEST_FILE_NAME
              value: manifest.json
            - name: OUTPUT_PATH
              value: /workspace/output_files
            - name: RUN_DATE
              value: "{{workflow.parameters.run_date}}"
            - name: SOURCE_ID_INDEX  # The source ID position in the input paths.
              value: "{{inputs.parameters.source_id_index}}"
            - name: SOURCE_PATH
              value: "/workspace/processed_files/{{inputs.parameters.source_type}}"
            - name: SOURCE_TYPE
              value: "{{inputs.parameters.source_type}}"
          command: [sh, -c]
          args: ["python3 /app/main.py"]