---
# General Git configuration for assignment workflows.
apiVersion: v1
kind: ConfigMap
metadata:
  name: metadata-git-repo-config
  namespace: argo-workflows-dev
  labels:
    # This label is required for the informer to detect this ConfigMap
    workflows.argoproj.io/configmap-type: Parameter
data:
  # Secrets
  git_secret_name: git-data-processing-metadata-key
  git_secret_file_name: ssh-private-key
  # Connection parameters
  git_repo_url: git@github.com:BattelleEcology/data-processing-metadata.git
  git_branch: main
  git_repo_name: data-processing-metadata
  # Directory names
  groups_directory: groups
  location_assets_directory: location-assets
  locations_directory: locations
  srf_directory: science-review-flags
  thresholds_directory: thresholds

  # Environment option
  GIT_BRANCH: main
  GIT_REPO: data-processing-metadata
  GIT_REPO_URL: git@github.com:BattelleEcology/data-processing-metadata.git